### ISSUE TITLE
Issue when passing path_model_init argument to train_model in train_network.py

### ISSUE THREAD

**Issue by oumayb** [neuropoly/axondeepseg#101]
When we pass the path to an existing model to train_model function in network.py, we get an error because the function global_variables_initializer in [line 328](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/train_network.py#L328) doesn't take any argument.

**Comment by oumayb** [comment]
@alzaia @jcohenadad I detected this, should I work on it?

**Comment by alzaia** [comment]
@oumayb Yes it would be a good practice for you to start using the pull request pipeline. You can find the full guidelines in this wiki page: https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution.

**Comment by alzaia** [comment]
This was merged into `dev_issue73` branch of PR #96, which got approved and already merged into `master`, so we can close this issue.
