### ISSUE TITLE
Add new blue/red display function for the segmentation masks

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axondeepseg#102]
@oumayb You did a small code for the RGB rendering of segmented masks in ADS (red/blue) 2 weeks ago, we should add it in the code as a new function before we forget. I suggest to put it under the ```visualization```subfolder, called something like ```rgb_rendering_of_mask.py```. It should take as input the grayscale 3-class mask (i.e. output of ADS) and return (and possibly save) the colored red/blue mask.

**Comment by oumayb** [comment]
Good idea @alzaia , I'm on it!
