### ISSUE TITLE
install sentry

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#115]
have a look at SCT project for inspiration on how to deploy sentry, and also how to announce opt in/out to the user.

**Comment by mathieuboudreau** [comment]
@jcohenadad Do you pay for a Sentry subscription for SCT? https://sentry.io/pricing/

If so, can you (or whoever is managing it for SCT) add me as a user so I can create/manage an AxonDeepSeg project within that organisation? 

If not, I'll create a free one for AxonDeepSeg (I only have a personal one right now to test it out), however I think that plan is limited to a single user (we'll need to share login info to all access the logs).

**Comment by jcohenadad** [comment]
@mathieuboudreau we use free license, which implies that reports are sent to a single email address pertaining to the organization. Because we don't want to merge reports from different projects (SCT, ADS, etc.), I've created a new Sentry organization as well as a new Gmail address specifically for AxonDeepSeg. Information added to the [wiki](https://github.com/neuropoly/axondeepseg/wiki/sentry).
