### ISSUE TITLE
command line support for TIF files?

### ISSUE THREAD

**Issue by ferozemohideen** [neuropoly/axondeepseg#119]
I get an OSError saying "Not a directory" when I try to pass in TIF files, but PNG works fine. How do I segment TIF files?

**Comment by mathieuboudreau** [comment]
Thanks for raising this issue @ferozemohideen – I'll take a look at it later this week!

**Comment by ferozemohideen** [comment]
Thanks Mathieu! I was trying to segment the following TEM image that was originally a TIF file I later converted into a PNG file:
![2_001c](https://user-images.githubusercontent.com/40551216/43101235-78f4a226-8e8d-11e8-8666-fdba8a233071.png)
However, when I segmented the image, this was the output:
![_segmented2_001c](https://user-images.githubusercontent.com/40551216/43101254-88cfc5a4-8e8d-11e8-9669-e30e9abd346e.png)
Do you think this could have occurred because of the conversion from TIF to PNG? Or is there another way to improve the output?

**Comment by mathieuboudreau** [comment]
Hmm, I'm going to ping @alzaia as he had more experience segmenting a large variety of datasets (and is the first author of the paper), so he might have an insight. If he doesn't respond by later this week, I'll take a look myself using the images you provided. Do you know what the resolution (per pixel) of your TEM image is?

**Comment by ferozemohideen** [comment]
Thanks! The size parameter I inputted was 0.007 microns.

**Comment by jcohenadad** [comment]
@ferozemohideen thank you for reporting the issue. I tried running the following with the image you uploaded on github:
~~~
axondeepseg -t TEM -i 43101235-78f4a226-8e8d-11e8-8666-fdba8a233071.png -s 0.007
~~~

and here is the result:
![anim](https://user-images.githubusercontent.com/2482071/43102830-3444ef70-8e9a-11e8-8156-f94aef20b2c4.gif)

could you please try running the code and let us know if you obtain the same result as I do? If not, could you please let us know which ADS version you are running? Thanks

**Comment by ferozemohideen** [comment]
Hi Julien, thanks for the quick reply. Unfortunately I ran the same command and received the same image as before as an output. I installed ADS today through pip so I believe I am up to date, but I don't know what I'm doing wrong.

**Comment by mathieuboudreau** [comment]
@ferozemohideen Ah ha, I just discovered last week that the pip version is quite out of date (v0.3 vs 0.4.2(stable) or 0.5(dev), so that may be the source of your issue. I will try to update that version soon.

In the meantime, if you'd like you could try downloading the latest version through GitHub (clicking the green "Clone or Download" button [here](https://github.com/neuropoly/axondeepseg), or better yet cloning it using the command-line `git clone https://github.com/neuropoly/axondeepseg.git`. Then open the directory with `cd axondeepseg`, and install it with `pip install -e .` (for more details, see Option 2 in the installation page of the wiki: http://axondeepseg.readthedocs.io/en/stable/documentation.html#installation).

Then run the command that @jcohenadad suggested, however note that you'll now be prompted (only once) for your consent for anonymous bug tracking, a new feature.

If that's a bit too complicated, then I'll let you know here when we've updated the PyPi version – sorry for this issue.

**Comment by mathieuboudreau** [comment]
I just tried in on both versions and reproduced @ferozemohideen 's segmented image using a venv installed with the latest pip version of ADS, and reproduced @jcohenadad 's segmented image on a venv installed with the current master version.
<details>

AxonDeepSeg v0.3 (pip)

![_segmented43101235-78f4a226-8e8d-11e8-8666-fdba8a233071](https://user-images.githubusercontent.com/1421029/43105766-a4b50266-8eb0-11e8-9a75-55c5bb221acc.png)

AxonDeepSeg `master`

![43101235-78f4a226-8e8d-11e8-8666-fdba8a233071_seg-axonmyelin](https://user-images.githubusercontent.com/1421029/43105775-a929b562-8eb0-11e8-8b94-a588deda908f.png)

</details>

**Comment by ferozemohideen** [comment]
@mathieuboudreau @jcohenadad thanks so much for your help, I got it to work now! As a quick question, if I am now trying to extract parameters like gratio, axon diameter, axon density, do I have to write my own script using the methods in your tutorial?

**Comment by oumayb** [comment]
@ferozemohideen there is a notebook that allows you to extract morphometrics from your predicted segmentation. It's here: https://github.com/neuropoly/axondeepseg/blob/master/notebooks/morphometrics_extraction.ipynb

**Comment by mathieuboudreau** [comment]
@ferozemohideen could you check if you're able to segment the *.tif image now that you've installed the latest version of ADS? TIF support may have been added between v0.3 (the first one you used) and the current master version.

**Comment by ferozemohideen** [comment]
@mathieuboudreau I just tried again and this time it gives me the error "The path specified is/are not image(s). Please update the input path(s) and try again."

**Comment by mathieuboudreau** [comment]
@ferozemohideen Ok thanks! I'll look into it.

**Comment by mathieuboudreau** [comment]
@ferozemohideen @jcohenadad One thing I just discovered is that I get that message if the extension is capitalised (*.TIF), but the processing works for me on a sample image if the extension is lowercase (*.tif), which means we have a case sensitive implementation. If that's the only bug related to this, it should be a simple fix.

**Comment by mathieuboudreau** [comment]
@ferozemohideen This issue should be resolved in the latest version of the master branch (it is for me), which will be included in the next PyPi release. If you encounter this issue again in the future when running ADS on the current (or future) version of master, please reopen this issue. (FYI: You'll have to either redownload ADS, or pull the new updates with `git pull` if you cloned it for these to be reflected on your local computer.)

**Comment by ferozemohideen** [comment]
@mathieuboudreau  @jcohenadad thanks so much for all your help!
