### ISSUE TITLE
Implement tools for axon-wise morphology metrics extraction based on output segmentation

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axondeepseg#12]
- similar structure to the AxonSegPy axonlist class structure
- how to extract myelin objects from output
- stats evaluation method : aggregated vs axon per axon

At the end, save the computed metrics as follows:

- add a flag for hdf5 output that contains already computed stats (diameter, circularity, solidity, centroid and g-ratio per axon)

**Comment by jcohenadad** [comment]
One possible approach for addressing this issue, would be to:
- from the axon+myelin mask, apply [watershed segmentation](http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_watershed.html)
- loop across objects. Multiply object *i* by ADS' output axon map to retrieve the axon segmentation of object *i*. Then, compute the equivalent diameter of the axon+myelin and axon to retrieve the axon-wise metrics of interest (g-ratio, etc.).
