### ISSUE TITLE
BUG: fail in call to generate_dict_da in train_model function in train_network.py

### ISSUE THREAD

**Issue by oumayb** [neuropoly/axondeepseg#122]
I'm trying to run the train_model function from the train_network.py file, and I get the following error message: "ValueError: need more than 2 values to unpack"

It's caused by this line:
https://github.com/neuropoly/axondeepseg/blob/2def1c0a022b009ba9c81ae96e9b3f36ab66f150/AxonDeepSeg/train_network.py#L52

that calls this one:
https://github.com/neuropoly/axondeepseg/blob/2def1c0a022b009ba9c81ae96e9b3f36ab66f150/AxonDeepSeg/train_network_tools.py#L82

It could be related to the changes in the config_file. https://github.com/neuropoly/axondeepseg/issues/114

**Comment by mathieuboudreau** [comment]
@oumayb could you post (or copy-pase) the config_network file you're trying to use?

**Comment by oumayb** [comment]
Sure, it's this one:

{
  "learning_rate_decay_period": 24000, 
  "batch_norm_decay_decay_period": 16000, 
  "learning_rate_decay_type": "polynomial", 
  "batch_norm_decay_decay_activate": true, 
  "learning_rate_decay_activate": true, 
  "learning_rate_decay_rate": 0.99, 
  "batch_norm_decay_ending_decay": 0.9, 
  "depth": 4, 
  "weighted_cost-activate": true, 
  "weighted_cost_balanced-activate": true, 
  "weighted_cost_balanced-weights": [
      1.1, 
      1, 
      1.3
    ], 
  "weighted_cost_boundaries_sigma": 2, 
  "weighted_cost_boundaries_activate": false,
  "batch_norm_activate": true, 
  "thresholds": [
    0, 
    0.2, 
    0.8
  ], 
  "trainingset_patchsize": 512, 
  "learning_rate": 0.001, 
  "downsampling": "convolution", 
  "batch_size": 8, 
  "da-type": "all", 
  "da-random_rotation-activate": false, 
  "da-noise_addition-activate": false, 
  "da-elastic-activate": true, 
  "da-shifting-activate": true, 
  "da-flipping-activate": true, 
  "da-rescaling-activate": false,
  "n_classes": 3, 
  "batch_norm_decay_starting_decay": 0.7, 
  "trainingset": "SEM_3c_512", 
  "size_of_convolutions_per_layer": [
    [
      5, 
      5, 
      5
    ], 
    [
      3, 
      3, 
      3
    ], 
    [
      3, 
      3, 
      3
    ], 
    [
      3, 
      3, 
      3
    ]
  ], 
  "dropout": 0.75, 
  "convolution_per_layer": [
    3, 
    3, 
    3, 
    3
  ], 
  "features_per_convolution": [
    [
      [
        1, 
        16
      ], 
      [
        16, 
        16
      ], 
      [
        16, 
        16
      ]
    ], 
    [
      [
        16, 
        32
      ], 
      [
        32, 
        32
      ], 
      [
        32, 
        32
      ]
    ], 
    [
      [
        32, 
        64
      ], 
      [
        64, 
        64
      ], 
      [
        64, 
        64
      ]
    ], 
    [
      [
        64, 
        128
      ], 
      [
        128, 
        128
      ], 
      [
        128, 
        128
      ]
    ]
  ]
}

**Comment by mathieuboudreau** [comment]
@oumayb yes it's related to the issue I raised that you mentioned. You'll just need to do the following renamings in your file:

weighted_cost_activate -> **weighted_cost-activate**
da-random_rotation-activate -> **da-2-random_rotation-activate**
da-noise_addition-activate -> **da-5-noise_addition-activate**
da-elastic-activate -> **da-3-elastic-activate**
da-shifting-activate -> **da-0-shifting-activate**
da-flipping-activate -> **da-4-flipping-activate**
da-rescaling-activate -> **da-1-rescaling-activate**

**Comment by oumayb** [comment]
@mathieuboudreau thanks a lot, it solved my issue. 
I also changed:
weighted_cost_boundaries_sigma -> **weighted_cost_boundaries-sigma**
weighted_cost_boundaries_activate -> **weighted_cost_boundaries-activate**
but I'm not sure about the first one.
