### ISSUE TITLE
[Refactor] Standardise how paths are handled

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#154]
Currently, some paths are handled with string manipulations,

https://github.com/neuropoly/axondeepseg/blob/003f9fa5874623e0941078e68d0c4839ae3ee8e0/AxonDeepSeg/data_management/input_data.py#L146

whereas others use the more OS-agnostic `os.path.join()` calls

https://github.com/neuropoly/axondeepseg/blob/003f9fa5874623e0941078e68d0c4839ae3ee8e0/test/test_config_tools.py#L126

but these are also a bit messy to maintain and to read from a users point-of-view. Since Python 3.4, a better way (in my opinion) to handle paths was added, which is using Path objects of the pathlib (https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f). 

The objects usually are handled correctly by functions (e.g. you can give a Path object to print, and it will convert it to a string to print), however it doesn't work well with string manipulations (e.g. you can't do `path_object + "Train/"`, you should instead do `path_object / "Train"` ). I ran into this error in #150 when giving Path objects to `train_model()` (fixed by converting them to strings first).

**Comment by jcohenadad** [comment]
Use module `pathlib`
