### ISSUE TITLE
can we utilize this architecture on other similar types of dataset such as cell segmentation or specially for  segmenting of phase contrast microscopy images?

### ISSUE THREAD

**Issue by Ayanzadeh93** [neuropoly/axondeepseg#160]
Hello, 
 I am working on the project that is related to segmentation of phase contrast microscopy image. I have a specific question about your architecture,

can we utilize this architecture on other similar types of the dataset such as cell segmentation or especially for segmenting of phase contrast microscopy images?

**Comment by jcohenadad** [comment]
Hi @Ayanzadeh93, yes it should be possible although you would need to train a new model.

**Comment by Ayanzadeh93** [comment]
> Hi @Ayanzadeh93, yes it should be possible although you would need to train a new model.

Thanks for your high consideration. 👍
