### ISSUE TITLE
Implement ADS as FSLeyes plugin

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#162]
Useful info here: https://github.com/neuropoly/spinalcordtoolbox/pull/1629#issuecomment-421737334

**Comment by Stoyan-I-A** [comment]
I'm currently trying to familiarize myself with FSLeyes. I was able to load a dataset and use the edit tool for manual segmentation.

It seems like FSLeyes does allow users to create plugins, as stated in the doc page 
https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/userdoc/latest/plugins.html

However I encountered a problem while trying to import a plugin.
I used the "Load plugin" menu item to load the test_plugin from https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/tree/master/tests/testdata/fsleyes_plugin_example
Once I did that, I was no longer able to launch FSLeyes. When I type "FSLeyes" in the command prompt, I get the following message :
![screen shot 2019-02-10 at 5 52 57 pm](https://user-images.githubusercontent.com/43790661/52541094-44261400-2d5f-11e9-801c-d194a0687c2a.png)

I used to be able to launch FSLeyes with just this command.
I tried to find another command that would start the application but I couldn't find one.

**Comment by mathieuboudreau** [comment]
@Stoyan-I-A Odd - can you open the FSL tool selector (command: `fsl`)? If so, can you open FSLeyes there? If not, what version of FSL do you have (number at the top of the GUI opened with `fsl`)?

**Comment by Stoyan-I-A** [comment]
I am able to open the FSL tool selector. The version is 5.0.8. But there is no option to open FSLeyes (I tried every button on the GUI).

I also tried uninstalling and reinstalling FSLeyes with pip uninstall. It didn't solve the problem, but I suspect there are other files related to the software in a directory called /usr/local that aren't modified. However, I don't know how to access this directory.

One command I tried is "fsleyes build". It returned the following error:
![screen shot 2019-02-11 at 1 19 55 pm](https://user-images.githubusercontent.com/43790661/52584342-ccf48c80-2dff-11e9-8732-43870844577c.png)

The version of fsleyes that I have installed is 0.27.3

**Comment by perone** [comment]
I think that the fsleyes installed with `pip` is the Python package itself, have you tried to install with the zip packages provided by their site: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes ?

**Comment by Stoyan-I-A** [comment]
Good news!
I tried installing FSLeyes with the zip package. It work! I was even able to load the example plugin.
I also managed to find the file that initially caused my problem and deleted it. I can now launch fsleyes through the terminal again. 

For future reference, when I first loaded loaded the exemple plugin, I selected the wrong file and it created a file in a hidden directory : "User/(username)/.fsleyes" and this was somehow causing an error.

**Comment by Stoyan-I-A** [comment]
It seems like FSLeyes allows me to use python packages that I have installed and that are not part of the 
original packages that come when installing FSLeyes. This means that I should be able to use the AxonDeepSeg's methods directly from the plugin script.

**Comment by Stoyan-I-A** [comment]
After fixing the tensorflow issue, I was able to run a plugin that imported AxonDeepSeg.

**Comment by Stoyan-I-A** [comment]
Here's my idea for the GUI design :
![image](https://user-images.githubusercontent.com/43790661/53924389-eaf18d80-4049-11e9-8c27-40465e6172ae.png)
This GUI will be attached to the FSLeyes window, under the image display.

The document containing this GUI design can be found in the google drive under /reports/20190306_FSLeyes_plugin_controls_GUI

Or simply by clicking this link: https://docs.google.com/spreadsheets/d/1S1c1CHo7kXiEZStI0ps_lHMfjyljJ2rLAVdCBEfsqkQ/edit?usp=sharing

**Comment by jcohenadad** [comment]
Nice start @Stoyan-I-A! Below is my suggestion (under sheet "Julien"):
<img width="876" alt="screen shot 2019-03-06 at 20 54 24" src="https://user-images.githubusercontent.com/2482071/53926598-14aeb280-4052-11e9-99af-3026eac6c48f.png">

The button `Apply myelin mask correction` would take a corrected myelin mask, and do the filling automatically to generate an updated axon mask.

**Comment by perone** [comment]
The layout is similar to the one we made for `sct_deepseg_gm` and `sct_deepseg_sc`, so you can base the code on the [code of the SCT plugin](https://github.com/neuropoly/spinalcordtoolbox/blob/master/contrib/fsl_integration/sct_plugin.py). There is code to add an image, to add a formatted citation and radio boxes as well.

**Comment by Stoyan-I-A** [comment]
Here's how the GUI looks now 
![Screen Shot 2019-03-10 at 5 04 29 PM](https://user-images.githubusercontent.com/43790661/54091933-82155880-435c-11e9-91a8-dca1bbe8ca53.png)

The borders of the ComboBox are a bit weird. I get the following warning when I load the plugin :

`2019-03-10 17:03:56.369 Python[32091:6624447] This application is trying to draw a very large combo box, 34 points tall.  Vertically resizable combo boxes are not supported, but it happens that 10.4 and previous drew something that looked kind of sort of okay.  The art in 10.5 does not break up in a way that supports that drawing.  This application should be revised to stop using large combo boxes.  This warning will appear once per app launch.
`

**Comment by Stoyan-I-A** [comment]
TODO: add a description that would appear when the cursor is on the buttons

**Comment by Stoyan-I-A** [comment]
How to hide the X and Y canvas:
https://github.com/pauldmccarthy/fsleyes/issues/20
