### ISSUE TITLE
Convert PNG images into a format that can be opened in FSLeyes

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#163]

**Comment by jcohenadad** [comment]
Use [nibabel](http://nipy.org/nibabel/) to convert png <--> nifti

**Comment by Stoyan-I-A** [comment]
Currently, the plugin allows the user to select a file PNG file and convert it to NIfTI. But the user has to manually load the NIfTI image into FSLeyes. As Julien said, it would be better if the image is automatically loaded into FSLeyes after the conversion.

Perhaps I should also add a button to export the segmentation masks into a PNG file afterwards.

**Comment by jcohenadad** [comment]
@Stoyan-I-A i suggest you create a "dummy" GUI with e.g. google sheet (e.g. take the current FSLeyes GUI and draw buttons), then add the link of this dummy GUI in this thread, then we can constructively make comments/suggestions

**Comment by Stoyan-I-A** [comment]
@jcohenadad Shouldn't I create a separate issue for the GUI design?

**Comment by jcohenadad** [comment]
> @jcohenadad Shouldn't I create a separate issue for the GUI design?

you can do the prototype design in https://github.com/neuropoly/axondeepseg/issues/162

**Comment by Stoyan-I-A** [comment]
I changed the button label to "Load PNG file" and made it so that the converted image is automatically loaded into FSLeyes

**Comment by Stoyan-I-A** [comment]
I send a message to the FSL mailing list to ask the developers if there's a way to directly load PNG images as an overlay.
The answer is no, but it's on their TODO list.
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1903&L=FSL&F=&S=&P=251142

**Comment by Stoyan-I-A** [comment]
TODO : the NIfTI files should be saved in a temporary folder

**Comment by Stoyan-I-A** [comment]
With commit 87f72ee , the NIfTI files are saved in a temporary folder. The automatic display was fixed a while ago.
