### ISSUE TITLE
Accessing Image/Overlay data in FSLeyes from a plugin script

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#164]
I am trying to figure out how to access the data from an image loaded in FSLeyes.

I tried to look at how it is done in the [spinalcordtoolbox plugin](https://github.com/neuropoly/spinalcordtoolbox/blob/master/contrib/fsl_integration/sct_plugin.py)
This script used commands such as:
`selected_overlay = displayCtx.getSelectedOverlay()` 
and
`overlayList.append(image)`

How is it possible to access the objects `displayCtx` and `overlayList`?

When I try to use them in my plugin script, I get an error saying that they are not defined.

Here's my code for the plugin script:

`import_ wx`
`import fsleyes.controls.controlpanel as ctrlpanel`
`import fsleyes`

`class Ads_control_v1(ctrlpanel.ControlPanel):`

    def __init__(self, *args, **kwargs):
        ctrlpanel.ControlPanel.__init__(self, *args, **kwargs)
        sizer = wx.BoxSizer(wx.VERTICAL)
        self.SetSizer(sizer)
        sizer.Add(wx.StaticText(self, label='Ads_plugin_v1_controls'),
                  flag=wx.EXPAND, proportion=1)

        adsButton = wx.Button(self, label = "Ads_pushbutton")
        adsButton.Bind(wx.EVT_BUTTON, self.onAdsButton)
        sizer.Add(adsButton, flag=wx.SHAPED, proportion=1)

    def onAdsButton(self, event):
        print(overlayList) # NameError: name 'overlayList' is not defined
        print(fsleyes.overlay.OverlayList.overlays) # This is not working

    @staticmethod
    def supportedViews():
        from fsleyes.views.orthopanel import OrthoPanel
        return [OrthoPanel]

**Comment by Stoyan-I-A** [comment]
@perone Perhaps you might have an answer to this. If not, it's okay, I'll keep searching.

**Comment by perone** [comment]
They changed this API so I'm not sure about it, have you tried to look if the `displayCtx` isn't being passed as the parameter on the `*args` or `**kwargs` of your constructors ? That would be a reasonable way to pass these parameters so I guess they might use that. You can also ask that in their mailing list or repository because they probably now that and will be able to answer immediately.

**Comment by Stoyan-I-A** [comment]
I contacted the FSL developers via their mailing list about this issue. Here's the link to their response :
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1902&L=FSL&F=&S=&X=9164C4158CCC55B25D&Y=stoyan.asenov.400%40gmail.com&P=216512

**Comment by perone** [comment]
Cool ! So they are indeed using the constructor parameters, that's good news.

**Comment by Stoyan-I-A** [comment]
I figured out how to test the plugins in debug mode. You were right.
The variables can be accessed with `self.overlayList` and `self.displayCtx` even with the ControlPanel class.
