### ISSUE TITLE
[Bug] Patches truncated for 16 bit images

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#166]
Likely due to this line: https://github.com/neuropoly/axondeepseg/blob/57047da51781c12d06c1b5d59dcb705bf4adc376/AxonDeepSeg/data_management/dataset_building.py#L44

Combining `preserve_range` plus `asint` may be what's truncating the patches (all white).

<img width="1221" alt="capture d ecran 2019-02-22 a 14 17 54" src="https://user-images.githubusercontent.com/1421029/53265949-022f9300-36ba-11e9-8b4e-77a662b72e30.png">

The solution may be as simple as removing the `asint` call.

@maxwab you wrote that line; do you see any issues with removing the `asint` call? I'll double check the rest of the code to make sure it's not assumed to be an 8bit int anywhere else. I guess it means that if I remove this, the data size will be much larger... Otherwise, removing the perserve_range could also possibly be a solution.

**Comment by mathieuboudreau** [comment]
@perone do you think there would be any issues in Tensorflow with having a mixed dataset (8bit + 16bit) during the training?

**Comment by maxwab** [comment]
Hi @mathieuboudreau,
At first glance I don't see any problem with removing the `.astype(int)` call.
The most likely reason I added this call at the time was to ensure the type of `img`. As far as I can tell, the reason was not memory usage.

**Comment by mathieuboudreau** [comment]
Thanks!

Poking around, although I was able to find where the images are converted toint  patches in the dataset building stage, but in the segmentation call the patches are separated by a different function, [`im2patchoverlap`](https://github.com/neuropoly/axondeepseg/blob/432af8265acc02401d8edd1e93e6e45b19471dbe/AxonDeepSeg/patch_management_tools.py#L33-L72), which doesn't appear to have an `int` conversion.

https://github.com/neuropoly/axondeepseg/blob/432af8265acc02401d8edd1e93e6e45b19471dbe/AxonDeepSeg/apply_model.py#L351

This is also slightly concerning that we are using two different parts of the code to create patches.

Maybe the short term solution for our current user who's dataset has a mix of 8bit and 16 bit files will be to just convert the 8bit files. I'll explore this and give them the option early next week.

**Comment by mathieuboudreau** [comment]
Actually, here are all the calls to `astype()`:

https://github.com/neuropoly/axondeepseg/blob/432af8265acc02401d8edd1e93e6e45b19471dbe/AxonDeepSeg/apply_model.py#L402-L403

https://github.com/neuropoly/axondeepseg/blob/432af8265acc02401d8edd1e93e6e45b19471dbe/AxonDeepSeg/apply_model.py#L402-L403

https://github.com/neuropoly/axondeepseg/blob/1edb7dd5bb3ccc2e1488015a3401b17b9b480cfd/AxonDeepSeg/data_management/dataset_building.py#L44

https://github.com/neuropoly/axondeepseg/blob/1edb7dd5bb3ccc2e1488015a3401b17b9b480cfd/AxonDeepSeg/data_management/dataset_building.py#L44

https://github.com/neuropoly/axondeepseg/blob/49795de3617e5a453c2b7bba36f2756f9cfcbc3c/AxonDeepSeg/data_management/input_data.py#L329

https://github.com/neuropoly/axondeepseg/blob/49795de3617e5a453c2b7bba36f2756f9cfcbc3c/AxonDeepSeg/data_management/input_data.py#L388

https://github.com/neuropoly/axondeepseg/blame/4fb50073a22d6358451567a4004236796d84058c/notebooks/analysis_proba.ipynb#L184

https://github.com/neuropoly/axondeepseg/blame/4fb50073a22d6358451567a4004236796d84058c/notebooks/analysis_proba.ipynb#L184

https://github.com/neuropoly/axondeepseg/blob/49795de3617e5a453c2b7bba36f2756f9cfcbc3c/AxonDeepSeg/testing/segmentation_scoring.py#L36

https://github.com/neuropoly/axondeepseg/blob/49795de3617e5a453c2b7bba36f2756f9cfcbc3c/AxonDeepSeg/testing/segmentation_scoring.py#L51

https://github.com/neuropoly/axondeepseg/blob/49795de3617e5a453c2b7bba36f2756f9cfcbc3c/AxonDeepSeg/testing/segmentation_scoring.py#L124

https://github.com/neuropoly/axondeepseg/blob/b3d9574d06739c7e52d2ce832b5efa90031a5f69/AxonDeepSeg/visualization/get_masks.py#L29-L30

https://github.com/neuropoly/axondeepseg/blob/1edb7dd5bb3ccc2e1488015a3401b17b9b480cfd/AxonDeepSeg/testing/noise_simulation.py#L36

https://github.com/neuropoly/axondeepseg/blob/1edb7dd5bb3ccc2e1488015a3401b17b9b480cfd/AxonDeepSeg/testing/noise_simulation.py#L57

https://github.com/neuropoly/axondeepseg/blob/1edb7dd5bb3ccc2e1488015a3401b17b9b480cfd/AxonDeepSeg/testing/noise_simulation.py#L75

https://github.com/neuropoly/axondeepseg/blob/476bb3fcf1a5092514c4c73d124a8e9f46d6015b/AxonDeepSeg/data_management/data_augmentation.py#L109-L114

https://github.com/neuropoly/axondeepseg/blob/476bb3fcf1a5092514c4c73d124a8e9f46d6015b/AxonDeepSeg/data_management/data_augmentation.py#L138-L145

https://github.com/neuropoly/axondeepseg/blob/476bb3fcf1a5092514c4c73d124a8e9f46d6015b/AxonDeepSeg/data_management/data_augmentation.py#L185-L191

**Comment by mathieuboudreau** [comment]
And here are the calls to `preserve_range`:

https://github.com/neuropoly/axondeepseg/blob/432af8265acc02401d8edd1e93e6e45b19471dbe/AxonDeepSeg/apply_model.py#L315-L317

https://github.com/neuropoly/axondeepseg/blob/476bb3fcf1a5092514c4c73d124a8e9f46d6015b/AxonDeepSeg/data_management/dataset_building.py#L41-L48

https://github.com/neuropoly/axondeepseg/blob/476bb3fcf1a5092514c4c73d124a8e9f46d6015b/AxonDeepSeg/data_management/data_augmentation.py#L75-L82

https://github.com/neuropoly/axondeepseg/blob/476bb3fcf1a5092514c4c73d124a8e9f46d6015b/AxonDeepSeg/data_management/data_augmentation.py#L138-L145

https://github.com/neuropoly/axondeepseg/blob/476bb3fcf1a5092514c4c73d124a8e9f46d6015b/AxonDeepSeg/data_management/data_augmentation.py#L265

**Comment by mathieuboudreau** [comment]
It may also be the "L" mode: https://github.com/python-pillow/Pillow/issues/3011

L mode is 8bit pixel (black and white): https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html
