### ISSUE TITLE
Check for solutions for the patch edges problem 

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axondeepseg#17]
Suggestions:

- use overlapping sliding window technique for the patch generation
- no need to apply it on small patches during testing time
- use different patch size for prediction and then combine overall results
- in input, enlarge the image (or patch) with mirroring at the edges (just 1 or 2 pixels padding)

**Comment by jcohenadad** [comment]
never close an issue without referencing to the commit that fixes the issue.

**Comment by jcohenadad** [comment]
duplicate of https://github.com/neuropoly/axondeepseg/issues/74
