### ISSUE TITLE
Extend functionality to handle images with any bit depth

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#170]
Extend functionality of AxonDeepSeg to handle images with any bit depth (would resolve #166), currently can only handle 8 bit.

**Things that may need to be done:**
  * [ ] Identify what combination of `.astype(int)`, ` preserve_range=True`, and `“L” mode` are causing the truncation for 16 bit.
  * [ ] Once identified, fix it in a way that retains the current functionality (i.e. either do better conversion to 8-bit that doesn’t truncate, or don’t do a conversion at all).
  * [ ] Write tests to verify that the new functionality doesn’t truncate 16b images anymore.
  * [ ] Demonstrate that the new functionality works for a non-8 bit image (or image dataset) in both the data patch splitting set and the training step.

**Potential roadblocks:**
* Lots of function that may be doing this conversion.
* Some functions may look at first glance like they might be doing this conversion, but may not and should remain untouched.
* Not converting high-bit images might result in large dataset sizes, so possible local space issues or tensorflow space issues.
* Ensure that unit tests pass, and if not identify if it’s because the changes made changed the API and:
  * could be avoided by proper refactoring
  * can’t be avoided with the new functionality, and the tests need to be changed.

**Comment by jcohenadad** [comment]
Database for testing: https://osf.io/yp4qg/

**Comment by mathieuboudreau** [comment]
`imageio.core.image_as_uint` might be a good converter for this task.

<img width="1106" alt="capture d ecran 2019-03-07 a 20 15 54" src="https://user-images.githubusercontent.com/1421029/53997222-e72b3d00-4115-11e9-9f68-48f1b3ef968f.png">

https://media.readthedocs.org/pdf/imageio/stable/imageio.pdf
