### ISSUE TITLE
`ads_utils.py:download_data`: Refactor to make proper use of exception and error handling

### ISSUE THREAD

**Issue by maf88** [neuropoly/axondeepseg#183]
Currently `download_data` is not returning an error if `Content-Disposition` is not the response header (`ads_utils.py:L189`). This should be in a try/except block. 
Also it would be nice to ask whether we should `return 1` or re-raise the error for this function. Then refactor as necessary.

**Comment by maf88** [comment]
wrong labels were applied and I wasn't able to change them. I closed and re-open it. See #184.

**Comment by mathieuboudreau** [comment]
Ok no worries. Next time however just ask for the label to be changed, since I apparently have access to do so (might be an admin feature).
