### ISSUE TITLE
Rename myelin output metrics

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#190]
Currently, for `get_axon_morphometrics` there are:
- myelin_diam --> outer diameter of  myelinated axon (axon + myelin)
- myelin_area --> surface of axon + myelin
See [lines](https://github.com/neuropoly/axondeepseg/blob/05cb434667350c84a4f0a5319d002fa6f5fb881b/AxonDeepSeg/morphometrics/compute_morphometrics.py#L125) in code.

this is not intuitive. The suggestion is to replace with:
- myelin_thickness --> outer equivalent circle minus inner equivalent circle [in mm]
- myelin_area --> surface of {axon + myelin} minus surface of {axon}

**Comment by maf88** [comment]
@jcohenadad  if we substract the axon area to the myelinated axon area, then the g-ratio can be higher than one, if we keep this formula: https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/morphometrics/compute_morphometrics.py#L129

Therefore I think that the g-ratio should be:

    gratio = SQRT( axon_area / axonmyelin_area )

What do you think?

**Comment by jcohenadad** [comment]
Sure, that’s how it has always been

**Comment by jcohenadad** [comment]
Read the introduction of this issue, maybe that’s how you got confused (ie; redefining myelin area)

**Comment by maf88** [comment]
In the actual code there is an ambiguity:

    myelin_area = axonmyelin_objects[ind_axonmyelin].area * (pixelsize ** 2)
    stats['myelin_diam'] = myelin_diam
    stats['myelin_area'] = myelin_area
    stats['gratio'] = np.sqrt(axon_area / myelin_area)

([source](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/morphometrics/compute_morphometrics.py#L129))

Was the g-ratio divided by the myelin area (name of the variable) or by what it represented (the area of the myelined axon)? I chose the former case, but apparently it should be the latter. 

I'll modify my code accordingly and I'll keep that in mind for the future ;-).

**Comment by jcohenadad** [comment]
> Was the g-ratio divided by the myelin area (name of the variable) or by what it represented (the area of the myelined axon)? I chose the former case, but apparently it should be the latter.

@maf88 originally, myelin_area (the variable and the stats output) was axon+myelin (as you probably figured out from the code). Hence, the gratio was correctly defined.

i agree this is confusing: this is precisely the purpose of this issue ;-)
