### ISSUE TITLE
Save the segmentations done in FSLeyes

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#191]
TODO : save the myelin and axon segmentation masks as three (3) separate PNG files :
- One will contain the Myelin mask
- One will contain the Axon mask
- One will contain both masks with different intensities

**Comment by mathieuboudreau** [comment]
Once you have the mask with Axon+Myelin, you can generate the other two separate images using this function:

https://github.com/neuropoly/axondeepseg/blob/b3d9574d06739c7e52d2ce832b5efa90031a5f69/AxonDeepSeg/visualization/get_masks.py#L10

**Comment by Stoyan-I-A** [comment]
I didn't use this function but I probably should. I'll have to change this eventually.
