### ISSUE TITLE
make the FSLeyes plugin code easier to understand

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#192]
TODO:
- Remove unnecessary blank lines
- Add docString at the start of functions/methods
- Comment parts of the code to explain what is being done

**Comment by Stoyan-I-A** [comment]
In my latest commits ( 4af6072 and e3ae8dd9d82000b7ed6c3ef59d92e097c6b0065c ), I added comments and descriptions for each function. If anyone has someone spare time, I would like to know if the plugin script is more clear. (?)

Also, I followed the [camelCase](https://en.wikipedia.org/wiki/Camel_case) convention for most of the variable names in the script, but it is not the convention used in the rest of the AxonDeepSeg project, so I should probably change that.

**Comment by mathieuboudreau** [comment]
See the PEP8 documentation for the standard Python naming conventions: https://www.python.org/dev/peps/pep-0008/#naming-conventions
