### ISSUE TITLE
[Project] Axon orientation

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axondeepseg#20]
Would be interesting to look at fibers orientation and generate maps.
To get fiber orientation histogram:
`````
Stats = regionprops(bwlabel(~~axonseg),{'Solidity','Eccentricity','Orientation','EquivDiameter','Area'});
u=[Stats.Orientation];
hist(u(~~u),100)
`````

![image](https://user-images.githubusercontent.com/7785316/29142476-11fc4382-7d20-11e7-9b3b-17261a5a99c7.png)

From that we should find the peak and compute std. Get a max angle. create maps.

**Comment by mathieuboudreau** [comment]
Stale
