### ISSUE TITLE
The docking of the FSLeyes plugin can't be automatically changed for now 

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#202]
As said in https://github.com/pauldmccarthy/fsleyes/issues/19 , the way the plugin is docked when initialized can't be changed for now. We have two options for the moment:
 1- Use an horizontal layout
 2- Ask the user to manually change the docking

Which one is preferred?

**Comment by jcohenadad** [comment]
definitely option 1

**Comment by Stoyan-I-A** [comment]
With the newest version of FSLeyes (which came out this week) this issue is now fixed.

**Comment by jcohenadad** [comment]
fixed in https://github.com/neuropoly/axondeepseg/commit/604f51374c3e0b32060aceb8199829169ef54813
