### ISSUE TITLE
FSLeyes plugin: Remove green cross once plugin has been loaded

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#204]
The green cross below is not relevant (only 2d view) and should be removed:
![image](https://user-images.githubusercontent.com/2482071/55684844-03411a80-591e-11e9-891b-f31380dfed86.png)

**Comment by Stoyan-I-A** [comment]
I'll take a look at this when possible. FSLeyes just made a new release and the developer documentation is currently blank.

**Comment by Stoyan-I-A** [comment]
Changes made with commit 7b6c4df
