### ISSUE TITLE
ImageJ as an alternative to FSLeyes for ADS plugin

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#214]
ImageJ is a well-maintained ecosystem, is dedicated to microscopy 2D data and accepts [plugins](https://imagej.net/index.php?title=Category:Plugins&pagefrom=SNT#mw-pages). So that could be a viable alternative to FSLeyes.

**Comment by jcohenadad** [comment]
also see: https://imagej.net/Trainable_Weka_Segmentation

**Comment by jcohenadad** [comment]
and this: https://deeplearning.cms.waikato.ac.nz/

**Comment by mathieuboudreau** [comment]
I think we're pretty cemented into sticking with FSLeyes now that it's working, so I'll close this issue.
