### ISSUE TITLE
Key error when data augmentation parameter : noise addition = True

### ISSUE THREAD

**Issue by vs74** [neuropoly/axondeepseg#223]
**Bug description**
While training network with data augmentation when noise addition is set to True, it produces the following  key error.
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../AxonDeepSeg/train_network.py:387: in train_model
    data_aug_verbose=data_aug_verbose)
../AxonDeepSeg/data_management/input_data.py:277: in next_batch_WithWeights
    augmented_data, data_aug_verbose)
../AxonDeepSeg/data_management/input_data.py:359: in apply_data_augmentation
    verbose=data_aug_verbose)
../AxonDeepSeg/data_management/input_data.py:62: in all_transformations
    L_transformations = generate_list_transformations(transformations, thresh_indices, verbose=verbose)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

transformations = {'elastic': {}, 'flipping': {}, 'noise_addition': {}, 'random_rotation': {'activate': False, 'order': '2'}, ...}
thresh_indices = [0, 0.2, 0.8], verbose = 0

    def generate_list_transformations(transformations = {}, thresh_indices = [0,0.5], verbose=0):
    
        L_transformations = []
    
        dict_transformations = {'shifting':shifting,
                                'rescaling':rescaling,
                                'random_rotation':random_rotation,
                                'elastic':elastic,
                                'flipping':flipping,
                                'gaussian_blur':gaussian_blur
                               }
    
        if transformations == {}:
            L_transformations = [functools.partial(v, verbose=verbose) for k,v in list(dict_transformations.items())]
        else:
            #print(transformations)
            L_c = []
            for k,v in list(transformations.items()):
                if (k != 'type') and (v['activate']==True):
                    number = v['order']
                    c = (number,k,v)
                    L_c.append(c)
            # We sort the transformations to make by the number preceding the transformation in the dict in the config file
            L_c_sorted = sorted(L_c, key=lambda x: x[0])
    
            # Creation of the list of transformations to apply
            for tup in L_c_sorted:
                k = tup[1]
                v = tup[2]
                list(map(v.pop, ['order','activate']))
>               L_transformations.append(functools.partial(dict_transformations[k], verbose=verbose, **v))
E               KeyError: 'noise_addition'

```

**To Reproduce**
1. Go to `AxonDeepSeg/test/test_train_network.py`
2. Set `"da-5-noise_addition-activate": True` in `self.config`
3. Run script `test_train_network.py`

**Comment by vs74** [comment]
I tried to resolve the issue actually there is no function named `noise_addition` in `data_augmentation.py`.  The function named is `Gaussian_blur` instead of `noise_addition`. So a fix to this issue might be replacing key value `noise_addition` by correct key name  that is `Gaussian_blur`. @mathieuboudreau  / @jcohenadad   what do you think about it ? Should I fix this by replacing the key name error in `config `file or perhaps is there  any other way around ?

**Comment by jcohenadad** [comment]
> I tried to resolve the issue actually there is no function named `noise_addition` in `data_augmentation.py`. The function named is `Gaussian_blur` instead of `noise_addition`. So a fix to this issue might be replacing key value `noise_addition` by correct key name that is `Gaussian_blur`. @mathieuboudreau / @jcohenadad what do you think about it ? Should I fix this by replacing the key name error in `config `file or perhaps is there any other way around ?

`Gaussian_blur` (i.e. smoothing 2D Gaussian kernel) sounds different than `noise_addition` (Gaussian noise added on a pixel-wise basis). So I would advise against making that replacement

**Comment by vs74** [comment]
I agree with you but there is no function defined in `data_augmentation.py` related to `noise_addition` instead there is a function named `Gaussian_blur`. Moreover in `input_data.py` the data augmentation dictionary has no parameter named `noise_addition `instead its having parameter named `Gaussian_blur`. So why are we using `noise_addtion` parameter when there is no functionality of it defined in ADS ? And secondly why `Gaussian_blur` which is impemented in `data_augmentation.py` not being mentioned in` config` file ?

**Comment by jcohenadad** [comment]
@alzaia can you help us here?

**Comment by vs74** [comment]
Yes I tried it was adding a gaussian filter to the image as what you said. Below is the  `mask 57` of `SEM_3c_dataset`
![Screen Shot 2019-06-28 at 3 03 39 PM](https://user-images.githubusercontent.com/31419210/60365310-5aeba100-99b6-11e9-8161-e7ba8b856571.png)
 After which I applied` Gaussian_blur` on it with` ('maximum sigma: ', 1.1507831018668693)`. Here is the image. 
![Screen Shot 2019-06-28 at 3 01 08 PM](https://user-images.githubusercontent.com/31419210/60365453-c170bf00-99b6-11e9-8bdf-0cbed49189bb.png)

**Comment by alzaia** [comment]
I think the only noise augmentation we used in our data aug. pipeline was the gaussian blurring. Not sure why it is called `noise_addition` in the dictionary though (maybe a refactoring issue at some point from us). 

I did do some noise addition on my own but that was unrelated to the data augmentation pipeline, it was just to [test the robustness to noise](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/testing/noise_simulation.py). 

So I'd say change the key to `gaussian_blur` instead of `noise_addition`. Or you can add both options and add some noise addition function inside the `data_augmentation.py` file (maybe something similar to [this](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/testing/noise_simulation.py#L6)).

**Comment by vs74** [comment]
Thanks @alzaia. I think for the time being I will change key` noise_addition` to  `gaussian_blur`as  it not required in current pipeline of data augmentation. If required later I will amend Gaussian_noise to the `data_augmentation.py` and `config file`.
