### ISSUE TITLE
Upgrade Tensorflow for CUDA 10 compatibility

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#225]

**Comment by mathieuboudreau** [comment]
I just quickly tried running the unit tests on rosenberg using tensorflow-gpu==1.14.0, and all the tests passed, so this might be an easier upgrade than anticipated.

**Comment by vs74** [comment]
Should I resolve this issue in  PR #221 or post it?

**Comment by mathieuboudreau** [comment]
Merge #221 first since I already thoroughly tested it on the older tensorflow version, then do this one in a separate branch.
