### ISSUE TITLE
[Project] G-ratio vs diameter

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axondeepseg#23]
Human data present two clusters of g-ratio VS diameter:
![image](https://user-images.githubusercontent.com/7785316/29142985-9c904d76-7d21-11e7-8a73-964e18e52979.png)

Why??
large g-ratio

![image](https://user-images.githubusercontent.com/7785316/29144142-dbbdfdf0-7d25-11e7-80f8-e43969296e50.png)

smallg
![image](https://user-images.githubusercontent.com/7785316/29144164-eaa8aa4a-7d25-11e7-8cb1-b7e95fdbe3ed.png)

to perform this kind of study. Use https://www.mathworks.com/matlabcentral/fileexchange/13857-graphical-data-selection-tool

**Comment by jcohenadad** [comment]
this issue is not specific to ADS
