### ISSUE TITLE
[Project] Separate touching myelin

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axondeepseg#24]
A script has already been developed to separate touching myelin in AxonSeg:
I tried it in folder `/Volumes/data_processing-1/tanguy/Histo/Human/AxonDeepSeg/20170527_HumanC5BG2_segmented`:
````
Myelin=imread('myelin_segmentation_37.png')>200;
Myelin = Myelin(2000:2500,3900:4300);
Axon=imread('axon_segmentation_37.png')>200;
Axon = Axon(2000:2500,3900:4300);

Myelin = Myelin | bwmorph(bwmorph(Axon,'thicken',2) & ~Axon,'close');
[Myelin,Nmy]=bwlabel(Myelin);
%[Axon,Nax]=bwlabel(Axon);

for ii=1:Nmy
    Myelinii=Myelin==ii;
    Myelinii = padarray(Myelinii,[1 1],1,'pre');
    Myelinii = imfill(Myelinii,'holes');
    Myelinii = Myelinii(2:end,2:end);
    
    markerBW = imfill(Myelinii, 'holes') & Myelin~=ii & Axon;
    touchingMyelinDist = -bwdist(markerBW);
    touchingMyelinDist(Myelin~=ii)=0;
    touchingMyelinDistinv = imimposemin(-touchingMyelinDist,markerBW);
    L = watershed(touchingMyelinDistinv,8);
    L(~touchingMyelinDist)=0;
    imagesc(L)
drawnow
end
````

![image](https://user-images.githubusercontent.com/7785316/29144390-cee37dca-7d26-11e7-94a6-515008c47418.png)

![image](https://user-images.githubusercontent.com/7785316/29144340-9bba8f38-7d26-11e7-98fa-06d8c6774207.png)

Currently it's based only on bw. would be nice to have different weight for small and large axons (more myelin in large axons), and use the image also.

**Comment by mathieuboudreau** [comment]
This was discussed and done in #768, I think using this model: https://github.com/axondeepseg/nn-axondeepseg
