### ISSUE TITLE
Weird outputs on coveralls

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#247]
https://travis-ci.org/neuropoly/axondeepseg/jobs/570662122#L771

doesn't seem like coveralls is doing much here...

**Comment by mathieuboudreau** [comment]
Are we sure it's not from Coveralls still being down?

**Comment by jcohenadad** [comment]
you're probably right, [older builds](https://travis-ci.org/neuropoly/axondeepseg/builds/566192428#L764) look fine.
sorry for the false alarm!

**Comment by jcohenadad** [comment]
p.s. wrongly assumed coveralls was up because other builds in SCT are working fine but i guess it's an intermittent issue...
