### ISSUE TITLE
Why is TEM image contrast being flipped, when model should be train on native TEM contrast

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#249]
See this code block:

https://github.com/neuropoly/axondeepseg/blame/aa285598371b089242db832ef2a4e8f804c7892c/AxonDeepSeg/segment.py#L64-L67

and issue #245

**Comment by mathieuboudreau** [comment]
Answer: because the contrast of the TEM patches that we trained were manually inverted. I'm going to try training an updated model with the uninverted contrast, and remove this hack.

**Comment by jcohenadad** [comment]
@mathieuboudreau is this issue fixed with the recently-trained model (without the manual flipping hack)?

**Comment by mathieuboudreau** [comment]
Resolved in #294.
