### ISSUE TITLE
Verify version of ads_plugin under fsleyes config folder

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#253]
Problem: If user updates ADS and the GUI changed, the user will not have the changes reflected in the currently-installed plugin.

Solution: have a caching system within the ads_plugin file, which would be verified upon calling of ADS. If ads_plugin is not up-to-date, make a pop-up window explaining how to update the ads_plugin file.

More info at: https://github.com/neuropoly/axondeepseg/wiki/fsleyes-plugin

**Comment by Stoyan-I-A** [comment]
Implemented in #182
