### ISSUE TITLE
Identify axon/myelin files based on the suffix

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#254]
Currently, in the GUI, the axon or myelin files are identified by looking for a string in the entire filename. This could be a problem if users call their file: axon12.png --> axon12-myelin.png, axon12-axon.png.

Solution: only work with suffix added by ADS, e.g. search for last string: "-myelin"  or "-axon".

**Comment by Stoyan-I-A** [comment]
Implemented in #182
