### ISSUE TITLE
[BUG, GUI] "Load Mask" button should load a mask with both axon and myelin, not axon or myelin.

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#270]
This feature requests comes from a user email.

See function here below. I don't see many cases where users want to load just an axon or just a myelin mask, it's better off if we make this button only support loading an image with both axon and myelin masks (for now at least, unless asked otherwise). This is also the behaviour the user expects when clicking this button (because there is no choice for loading either myelin or axon masks, these are details only the developers are aware of from the code). This is because the user manually corrected masks and saved them, but now wants to load them. I understand that they could load both the individual myelin and axon masks (this is what I will suggest in short term), but I think in the long term it's unmanageable to require these three separate files, as there's no way to ensure they're in synch (i.e. if they use another software to fix only the axon-myelin mask.)

https://github.com/neuropoly/axondeepseg/blob/b670f5f252f27ca07aad19e893f9ee7fbffe7d75/ads_plugin.py#L236-L266

**Comment by jcohenadad** [comment]
Agreed, let's limit to axon+myelin masks. We should specify it in the ads_plugin docstrings, including specifications of this mask (values for myelin and axons, data format, number of channels, etc.)

**Comment by mathieuboudreau** [comment]
Resolved in #271
