### ISSUE TITLE
Image dimension consistency issue while performing patching

### ISSUE THREAD

**Issue by vs74** [neuropoly/axondeepseg#273]
**Bug**
When patching is performed on a raw dataset to create image of a fixed patch size ( for example `512 X 512 `), it produces images of different dimension ( here in this case some images were of `511 X 512` other's of `512 X 511` dimension). For detailed information see[ here](https://github.com/neuropoly/axondeepseg/pull/226#issuecomment-548898381)

**Comment by mathieuboudreau** [comment]
See proposed solution here: https://github.com/neuropoly/axondeepseg/pull/226#issuecomment-548945688

**Comment by vs74** [comment]
Closing this issue as have been solved in PR #226 .
