### ISSUE TITLE
Training Issue: Cannot locate image

### ISSUE THREAD

**Issue by Paasu** [neuropoly/axondeepseg#280]
**Describe the bug**
Says the it cannot locate image_1920.png. The images in the folder go up to image_1919.png. 

**To Reproduce**
Running the training guidline notebook. We used a modified version.

**Desktop (please complete the following information):**
 - OS: Linux Solus Budgie
 - Version 4.1

[error.txt](https://github.com/neuropoly/axondeepseg/files/4176842/error.txt)
[training_guideline.txt](https://github.com/neuropoly/axondeepseg/files/4176843/training_guideline.txt)

**Comment by mathieuboudreau** [comment]
Hi @Paasu! It sounds like to me that it's looking for an image patch beyond what you generated. Not sure why this would come up in the training guidelines notebook. To help debug, could you please share the following things:

1 - The branch that you're using the code on/
2- The git commit # if you know it
3- Are you using some of the data that we provided, or your own data? If you're using your own, would you mind sharing a raw image and raw mask?
4- The training_guideline exported as a iPython Notebook file (*.ipynb).

Thanks!

**Comment by Paasu** [comment]
Hi, thank you for responding.

1. The branch we used was axondeepseg-master.
2. We didn't use git, we just cloned from github
3. We are using our own data.
![image](https://user-images.githubusercontent.com/50454820/74244141-e3fee080-4cd8-11ea-9dd1-58aa59d00918.png)
^ Above is one of the images we are using in training. I was unsure what the mask image was meant to be, I assumed it to be a copy of the raw image renamed mask.png.
4. We used training_guidline as a python file because for some reason jupyter wasn't working.
[training_guideline.zip](https://github.com/neuropoly/axondeepseg/files/4186161/training_guideline.zip)

Thank, hope everything goes well!

**Comment by mariehbourget** [comment]
Hi @mathieuboudreau ,
Here are the tests I have done so far:
1) I have run the guide_dataset_building notebook to generate patches from the image.png and mask.png from data_test in AxonDeepSeg.
2) Then I ran the notebook training_guideline sent by Paasu on the master branch.
I was unable to reproduce the problem while training, all the images are located correctly.

**Comment by Paasu** [comment]
Hello everyone,

I have fixed the issue. I attempted everything a second time but on a different OS (OpenSUSE Leap 15.1) and so far the training works, the final test display of an image will not work however, I will post a new issue for that.

Thank you everyone for the help!
