### ISSUE TITLE
dataset building

### ISSUE THREAD

**Issue by AlmudenaRobledo** [neuropoly/axondeepseg#281]
I am trying to prepare a data set to train a model. I created folders with the raw images and manually made myelin masks (using GIMP) and am running the guide_dataset_building notebook but I get the following errors: 

"ValueError: Max value == min value, ambiguous given dtype" when splitting the dataset into patches

Any help is appreciated!

**Comment by mathieuboudreau** [comment]
@AlmudenaRobledo did you resolve your issue? If so, would you mind sharing what you did?

**Comment by AlmudenaRobledo** [comment]
No, sorry, I opened a new issue with more details and other problems I am having thinking it might be more helpful. 
Thanks!

**Comment by mathieuboudreau** [comment]
Ok no worries! I'll just comment here that you moved your issue to #282 for future reference.
