### ISSUE TITLE
Remove hardcoded paths in download_data()

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#286]
Introduced when merging #226 

https://github.com/neuropoly/axondeepseg/blob/dae4a1dcd90539cfcc7347d38cb8264395de8a66/AxonDeepSeg/models/download_model.py#L12-L13

Should probably used the Path() function as well as relative paths to the main repo location.

**Comment by mariehbourget** [comment]
I'm closing this issue because it is resolved with PR #322
