### ISSUE TITLE
Format Changelog

### ISSUE THREAD

**Issue by vs74** [neuropoly/axondeepseg#287]
**Describe the bug**
After the merge of PR #226, In [RTD](https://axondeepseg.readthedocs.io/en/latest/documentation.html#changelog) under the **changelog.MD** section specifically version 3, the changes have been poorly formatted, unlike the previous changes where each change was separated by bullet points. 

See the screenshot attached for more information

<img width="752" alt="Screenshot 2020-03-17 at 4 39 59 PM" src="https://user-images.githubusercontent.com/31419210/76875006-4024c980-6870-11ea-93f2-b2c9d79854f4.png">

**Comment by mathieuboudreau** [comment]
Great thanks! That might be a small formatting issue, like wrong number of spaces or tabs instead of spaces.

**Comment by vs74** [comment]
> Great thanks! That might be a small formatting issue, like wrong number of spaces or tabs instead of spaces.

@mariehbourget, can take a look at it since she is working on Documentation.

**Comment by mariehbourget** [comment]
349271f
