### ISSUE TITLE
FSLeyes: Clarify "Load existing mask" button behaviour

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#299]
The plugin expects a combined axon-myelin mask but the title text of the button says otherwise.

![Screen Shot 2020-05-15 at 11 19 18 AM](https://user-images.githubusercontent.com/54086142/82098719-82815000-96d3-11ea-93b5-a9bddc23a553.png)

**Comment by Stoyan-I-A** [comment]
Ah, I forgot to update the tooltip when I changed the behaviour of the button a while ago. I'll have to update it before merging #296

**Comment by Stoyan-I-A** [comment]
Resolved in #296
