### ISSUE TITLE
How to save segmentation

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axondeepseg#30]
My feeling, 2 options:
- save axonlist dictionary:
PROS: subpixel resolution (output of AxonSeg snake)
            Can save touching myelin
  - json file is not suitable for very large datasets (no compression). 
  - HDF5: better, very standard format designed for very large datasets https://support.hdfgroup.org/HDF5/whatishdf5.html. (used in Matlab save)
- Save myelin mask:
CONS: myelin need to be separated and closed
            cannot save extra info (e.g. diameter, myelin thickness)
  - png: cannot read a subregion + size limit of 4Gb
  - tiff: limit of 4Gb... note that we go over this limit in Human datasets (~100,000x100,000 = 10Gpx)

**Comment by alzaia** [comment]
Added code to save axon and myelin masks during segmentation. Resolved in commits eadefba815bfd4e33f7437ac1227d23cd602651a and 42810475481ee0c0bd51b8879879db412cbb37a2.

Also added corresponding jupyter notebooks for output separation into 2 masks (axon + myelin) + merging back to combined label mask.

Note: these masks will also be useful if the user wants to manually correct the segmentation output.

Note: the hdf5 save of the computed stats was added to the corresponding issue (issue #12) as it first requires the pipeline to obtain these merics on axondeepseg.
