### ISSUE TITLE
Consistency in contribution guidelines

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#302]
There are 3 different ways to name branches for contribution across the documentation.
dev_issue_# (in Wiki [here](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution#procedure-to-submit-a-pull-request-pr-for-new-devfeaturesimplementations))
inital_issue# (in Wiki [here](https://github.com/neuropoly/axondeepseg/wiki/Rules-for-commits-and-issues-labelling-(git)#branch-and-pull-requests))
initals/description (in CONTRIBUTING.rst [here](https://github.com/neuropoly/axondeepseg/blob/master/CONTRIBUTING.rst#naming-your-branch))

We should establish a convention and correct the doc.

**Comment by jcohenadad** [comment]
Let’s go with initials/description (if no issue) or initials/issue-description

**Comment by mariehbourget** [comment]
I've made the changes in Wiki ([here](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution#procedure-to-submit-a-pull-request-pr-for-new-devfeaturesimplementations) and [here](https://github.com/neuropoly/axondeepseg/wiki/Rules-for-commits-and-issues-labelling-(git)#branch-and-pull-requests)).
Should I close the issue?
