### ISSUE TITLE
Set a specific version of FSLeyes to use for the plugin.

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#303]
There are a few problems with the most recent versions of FSLeyes
- FSLeyes 0.33.0 only supports python 3.7 and above.
- Mathieu reported that the plugin was not showing up on the menu-bar on FSLeyes 0.32.3 (although this wasn't the case for me)

Also, the installation of FSLeyes on Linux doesn't work with pip anymore. It must be installed with conda-forge. The documentation must then be updated.

I'd suggest using FSLeyes 0.30.1

**Comment by mathieuboudreau** [comment]
Is 0.30.1 the last version that they updated the software with a feature we requested?

**Comment by Stoyan-I-A** [comment]
Yes. According to the [changelog](https://users.fmrib.ox.ac.uk/~paulmc/fsleyes/apidoc/latest/changelog.html), that's when they fixed 2D image editing.

**Comment by mathieuboudreau** [comment]
I just tried with version 0.32.3 and it worked for me now. This is the FSLeyes version that was pulled from conda when I made the command `yes | conda install -c conda-forge fsleyes` inside a Python 3.6.x virtual environment, so it looks like the FSLeyes folks knew about that limitation for 3.7. We could upgrade ADS to 3.7 (the tests passed the last time I checked), or fix the FSLeyes version to 0.32.3 if we want to stay on 3.6. I'd vote for upgrading to 3.7 - no use being stuck in the past, and we have a good set of unit tests to give us a good sense of secutiry that the upgrade shouldn't break the main functionality.

>On another note, if I try to install AxonDeepSeg two times on a virtual environment, I get an error that seem to be related to setup.py (possibly because it's trying to download models that are already present in the repository, I'm not sure. If I delete the models from the repository, the installation works)

Yes, I've encountered this when I checked as well. Seems like there should be a check to see if we already have downloaded the model, or overwrite the model if we're re-runing `pip install -e .`. @vs74 could look into this?

**Comment by vs74** [comment]
> I just tried with version 0.32.3 and it worked for me now. This is the FSLeyes version that was pulled from conda when I made the command `yes | conda install -c conda-forge fsleyes` inside a Python 3.6.x virtual environment, so it looks like the FSLeyes folks knew about that limitation for 3.7. We could upgrade ADS to 3.7 (the tests passed the last time I checked), or fix the FSLeyes version to 0.32.3 if we want to stay on 3.6. I'd vote for upgrading to 3.7 - no use being stuck in the past, and we have a good set of unit tests to give us a good sense of secutiry that the upgrade shouldn't break the main functionality.
> 
> > On another note, if I try to install AxonDeepSeg two times on a virtual environment, I get an error that seem to be related to setup.py (possibly because it's trying to download models that are already present in the repository, I'm not sure. If I delete the models from the repository, the installation works)
> 
> Yes, I've encountered this when I checked as well. Seems like there should be a check to see if we already have downloaded the model, or overwrite the model if we're re-runing `pip install -e .`. @vs74 could look into this?

@mathieuboudreau , I saw your comment on this too late.( I might have missed somehow the email from GitHub or might have skipped it) However, you are right and we should fix the ADS  to prevent it from overwriting models if already present. I will open a PR which will implement this behaviour.

**Comment by pauldmccarthy** [comment]
I just saw this issue - apologies for unncessarily causing you work. You may have already realised that the latest version of FSLeyes should be compatible with python 3.6. The reason that I originally marked it as >=3.7 was because of a missing dependency on `dataclasses` (introduced in Python 3.7). But installing the backport in 3.6 solves the problem, so you should be ok to use python 3.6.
