### ISSUE TITLE
Bump to Python 3.7

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#306]
Motivation: https://github.com/neuropoly/axondeepseg/issues/303

**Comment by mariehbourget** [comment]
All tests passed in python 3.7.
@mathieuboudreau @Stoyan-I-A Do we want to keep both 3.6 and 3.7 in the setup `python_requires='>=3.6, <3.8'` or 3.7 only `python_requires='>=3.7, <3.8'` for FSLeyes?

**Comment by jcohenadad** [comment]
seems easier to just "force" 3.7+ to avoid problems with fsleyes

**Comment by mathieuboudreau** [comment]
> seems easier to just "force" 3.7+ to avoid problems with fsleyes

+1 from me. Either force exactly 3.7 or 3.7+ (if we do the latter, we should include those others in the Travis tests).

**Comment by mariehbourget** [comment]
Ok, so I'll go with `>=3.7, <3.8`.
As to "include those others in the Travis tests", I don't know what that means.

**Comment by mathieuboudreau** [comment]
E.g. https://gist.github.com/al45tair/34fdf558dd6c318a63c1ec9166b99c2e<https://gist.github.com/al45tair/34fdf558dd6c318a63c1ec9166b99c2e>

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by mariehbourget** [comment]
Thanks, i'll update the Travis tests as soon as possible.
So we want to test all versions from 3.7.0 to 3.7.7 ?

**Comment by jcohenadad** [comment]
if you go with >=3.7, why not simply testing for 3.7 and 3.8?  why testing for patches (i.e. 3.7.1, etc.)

**Comment by mariehbourget** [comment]
As discussed with Julien, some dependencies are not compatible with 3.8, so we'll keep 3.7 only for now. Also, I suggest we change the version to 3.2 in order to update the documentation [here](https://axondeepseg.readthedocs.io/en/latest/documentation.html#miniconda).

**Comment by mariehbourget** [comment]
> Also, I suggest we change the ADS version to 3.2 in order to update the documentation [here](https://axondeepseg.readthedocs.io/en/latest/documentation.html#miniconda).

@jcohenadad @mathieuboudreau Are you ok with a change to ADS version 3.2?
