### ISSUE TITLE
Create a CLI in ADS using ivadomed API for segmentation

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#309]
**AIMS**
- Integrate `ivadomed` and `pytorch` as requirements for ADS
- Create a CLI using ivadomed API for inference/segmentation with pre-trained ivadomed models
- Adapt performance measures and morphometric extractions of ADS between ivadomed output and ADS input
- Remove code/requirements specific to training and inference

**Strategy**
- We need to come up with a strategy for the transition
- We may need to do this in several steps
- We may need to support both version simultaneously for a while:
    1. ADS training + inference/segmentation with `tensorflow`/`keras`
    2. ivadomed inference/segmentation with `pytorch`

**Related issues**
- Issue #327: Upgrade ADS requirements to be compatible with ivadomed
- Issue #515: Is axondeepseg compatible with anisotropic pixel sizes?

**Comment by vs74** [comment]
I'm planning to start working on this issue specifically 
>Create a CLI using `ivadomed` API for inference/segmentation with pre-trained `ivadomed` models
>Adapt performance measures and morphometric extractions of ADS between `ivadomed` output and ADS input


As @mariehbourget and @mathieuboudreau are planning to discuss the next steps of actions for the transition from TensorFlow based Keras framework (ADS default training behavior) to `ivadomed` (PyTorch), feel free to either include me in the discussion or document the discussions here in this issue.

**Comment by mariehbourget** [comment]
Here is an overdue update on this issue:

- The strategy for the integration of ivadomed and version 4 of ADS is being discussed in #523.
- Implementation of v4 is in-progress with PRs:
    - #539
    - #546
    - #547

**Comment by mariehbourget** [comment]
I'm closing this issue now that ADS v4.0.0 is released using ivadomed's segmentation models!
