### ISSUE TITLE
Stereology Measures

### ISSUE THREAD

**Issue by amoebacodes** [neuropoly/axondeepseg#314]
I have noticed that in the AxonDeepSeg paper, a grid is applied to small 512 x 512 pixels patches to overcome "border issues", meaning some axons land on the edges and thus are not properly analyzed. However, it is an issue still for axons on the edge of an entire image. 

Stereology measures could be utilized to circumvent this issue. As shown in the picture in the link below, a central area of the image can be carved out for analysis, whereas the crust can be used to assist analysis of axons that are on the border.
http://www.stereology.info/counting-rules/

Thank you for reading this and for considering this suggestion!

**Comment by mariehbourget** [comment]
Hi @amoebacodes,
Thanks for bringing that method up to our attention.

In AxonDeepSeg, we use an overlap to properly analyse axons landing on the edges of patches. That overlap acts as the crust from your example with stereology measures, and assist analysis on the border of the central area of patches.
For example, with a patch of 512x512 and an overlap of 25, the segmentation is performed on the entire patch of 512x512 for context, but only the 462x462 central area is output without the overlap. When all patches are analyzed, the 462x462 patches are then stitches together in the final segmentation (the overlap being used only for patches at the very edges of the image).

Let us know if you have more questions about patches behavior or if I misinterpreted your suggestion.
