### ISSUE TITLE
doc: install

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#32]
after install, add a test to make sure install worked.

**Comment by alzaia** [comment]
resolved in commits 4d7e0ee9540921587bc8c0132a912ed62a1c96c1 and 6c7d20a2fa3a19b323b3c1e87ded2c943a7e344e.

Notes: added basic integrity test script that can be launched after installation to see if the installation succeded. The test launches basic axondeepseg operations on a test dataset. 
Test dataset was also added on setup.py to be included in all future wheels.

**Comment by jcohenadad** [comment]
reopened, see:
https://github.com/neuropoly/axondeepseg/commit/6c7d20a2fa3a19b323b3c1e87ded2c943a7e344e#r26399752

**Comment by alzaia** [comment]
Resolved with PR #40
