### ISSUE TITLE
FSLeyes plugin overlapping myelin & axon corrected masks behaviour?

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#321]
When drawing on the masks in the plugin, what happens if we "draw outside the lines" and have overlapping myelin and axon masks? Is there a bug that we need to fix to get proper behaviour? Which one should take priority (axon or myelin?)

**Comment by Stoyan-I-A** [comment]
Just tested it. Currently, Myelin takes priority on the combined masks image. However, on the images with individual masks, those are saved without the "priority correction".
