### ISSUE TITLE
Make testing images for SEM and TEM available on OSF

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#333]
We want to upload 1 image for SEM and 1 image for TEM on OSF for testing our models.

Those images should:
- not be part of the training datasets currently on [OSF](https://osf.io/jwxyz/) in `data/raw/SEM_dataset.zip` and `data/raw/TEM_dataset.zip`.
- have a manual mask to evaluate model performances

TEM chosen image is: `20160718_nyu_mouse_26_0004`
SEM chosen image is: `data15`

Each image and mask will be package with a README file in a zip and upload on OSF.

The main README file also have to be updated to reflect those changes.

**Comment by mathieuboudreau** [comment]
@mariehbourget email them to me and I'll upload them to OSF. Do you want them to be in the same ZIP files as the current datasets, or added as separate files next to the zip?

**Comment by mariehbourget** [comment]
I would prefer to have them in separate zip files, I'll prepare everything and email them to you when they are ready (after the meeting). Thanks.

**Comment by jcohenadad** [comment]
how about we instead set up repos under a new axondeepseg organization, as this will eventually be our next strategy. ie: why not starting doing this now.

**Comment by jcohenadad** [comment]
Context:
- currently, "generic" test images are located at: https://github.com/neuropoly/axondeepseg/tree/master/AxonDeepSeg/data_test
- note: some specific files used for unit testing are also located [there](https://github.com/neuropoly/axondeepseg/tree/master/test/__test_files__)

Problem:
- the current generic test image is used in the training
- there is no provenance information that enable us to properly link this image with future models
- only SEM image

Proposed strategy:
- package a test image alongside each model (one for SEM, one for TEM, etc.)
- update some tests + notebooks to point to these new test images

**Comment by mariehbourget** [comment]
The testing images are ready. As discussed, i packaged them inside our default models folders.
I uploaded the new zip folders on ADS google drive [here](https://drive.google.com/drive/folders/1d6dsGA7MCVvLPWWQSD7A4y6hvOocYBHl).
There is also a README file to update the main README file on OSF.

I will make the changes to notebooks and tests after my vacation.

I have a question though:
If the data_test images are located inside the models folder, when segmenting them with the notebooks, by default the segmented files will be in this folder to. If we then re-install ADS, the defaults models will be redownload and replace the previous folders. Any segmentations saved in that folder will be lost. I'm not sure if this is relevant since it is suppose to be only testing files and not suppose to be a place to store segmentation results permanently.

**Comment by jcohenadad** [comment]
since it’s only for testing purpose it’s fine

**Comment by mariehbourget** [comment]
The testing images inside default models folders are now uploaded to OSF (as of 2020-08-21, version 5).
@mathieuboudreau can you also upload the new README file that replace the main README on OSF? Thanks!

**Comment by mathieuboudreau** [comment]
@mariehbourget which README file did you want me to re-upload exactly?

**Comment by mariehbourget** [comment]
@mathieuboudreau Sorry, I wasn't clear. The  file is located with the new models you uploaded 2 weeks ago [here](https://drive.google.com/drive/folders/1d6dsGA7MCVvLPWWQSD7A4y6hvOocYBHl).
So the README file that is outside the models folders should replace the main README file on OSF. Thanks!

**Comment by mathieuboudreau** [comment]
Thanks for clarifying! Done!
