### ISSUE TITLE
FSLeyes: Overlay axon numbers on the image

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#341]
As suggested by one of our user: after computing morphometrics, it would be nice to be able to show the axons numbers (in the first column of the xls file) over the image in FSLeyes. It would be useful to identify rapidly the legitimate axon+myelin pairs when the model identifies small fragments outside of myelin as axons by mistake.

**Comment by jcohenadad** [comment]
> This might be difficult to implement because I don't think FSLeyes has some built-in functions that allow to write text over overlays. I could be wrong though. So, if anyone knows an existing feature in FSLeyes that does something similar, let me know.
> 
> Another possible option would be to create an overlay (a "mask") on which there would be pixelated numbers at the coordinates listed in the morphometrics.

the best person to ask is @pauldmccarthy

**Comment by Stoyan-I-A** [comment]
I asked in https://github.com/pauldmccarthy/fsleyes/issues/60 whether there was a way to display text. There's an annotation feature, but its functionality is limited. I'll have to play a bit with this feature to find out what we can do with it.

**Comment by Stoyan-I-A** [comment]
I tested the annotation feature, and it is not useful in its curent state.
The annotation is essentially attached to the FSLeyes canvas where the image is displayed, not on the image itself. 
This means that the text will stay at the same location on the screen if the user decides to zoom on the image, which is inconvenient.

Perhaps the best solution at the moment is to go with the approach where we create an overlay with prixelated numbers.

**Comment by jcohenadad** [comment]
> Perhaps the best solution at the moment is to go with the approach where we create an overlay with prixelated numbers.

sounds good to me

**Comment by Stoyan-I-A** [comment]
Here's how it looks at the moment in PR #342
![image](https://user-images.githubusercontent.com/43790661/90802441-41599700-e2e5-11ea-87dc-04b96af58f74.png)
