### ISSUE TITLE
Installation, training and morphometrics

### ISSUE THREAD

**Issue by Paasu** [neuropoly/axondeepseg#345]
**Describe the bug**
I have a few issues I would like to resolve. 
First, AxonDeepSeg fails to install on multiple computers (Windows, OpenSUSE, Ubuntu), the only version that works is on python 3.6 instance of miniconda. Here is the error log I receive everytime I try to install it.
[error.txt](https://github.com/neuropoly/axondeepseg/files/5179840/error.txt)

Second, after I manually updated the AxonDeepSeg, it requests that I install Tensorflow 2.2 everytime I try to train the , but when I try the install fails; it requires 2 dependencies to install which when I try installing, it doesn't actually install even though it says install successful, my guess is that it is just an issue with my OS, I think it might be best to clean install a new linux version. What do you guys think?

Third, I tried testing the morphometrics on the manual masks to test the efficacy of the data compared to my manual measurements. I do understand that it was the manual masks and not the segmented images so it might be the reason the data differs significantly. The reason I haven't used the masks to train and the use the segmented images to analyze is because of the second problem mentioned above.
[Neuron Morphometrics.pdf](https://github.com/neuropoly/axondeepseg/files/5179934/Neuron.Morphometrics.pdf)

I only used a very small sample of 4 masks but there seems to be a significant difference in g-ratio, and myelin thickness with smaller but present differences in axon diameter. Is it possible because my masks aren't high quality enough?
[Images.zip](https://github.com/neuropoly/axondeepseg/files/5179946/Images.zip)

**Desktop (please complete the following information):**
 - OS: [OpenSUSE/Windows]
 - Version [15.1/10]

**Comment by mathieuboudreau** [comment]
Hi @neuropoly/qdlab 

Per our documentation (https://axondeepseg.readthedocs.io/en/latest/documentation.html#installation), we don't actively test the installation on Windows using our continuous integration tests, so working with Windows is expected to be very unstable. One of us that have a Windows computer (I don't) can likely take a look at the bug to see if is easily fixable, however for better stability I would strongly recommend you use a virtual machine running Linux (e.g. [see here](https://www.youtube.com/watch?v=5sa0acU4pmY)) or if you don't plan to use the FSLeyes addon, Docker could be an alternative.

**Comment by Paasu** [comment]
I understand I do all my tests on linux based OS, the problem is the issue shows up even on linux. I do create a conda environment on my linux and then install AxonDeepSeg, maybe that's the problem? And what's your take on the other 2 issues?

**Comment by jcohenadad** [comment]
>  And what's your take on the other 2 issues?

@Paasu it makes management more difficult for us when a single issue on Github includes multiple issues that are unrelated. Could you please open separate issues, with a specific title pertaining to each issue you are having, specifying the version of ADS you are running, example data, the syntax you are using, etc. Then, we will address each of your issue separately.

**Comment by Paasu** [comment]
@jcohenadad 
Sorry about that, I just separated into different issues. Let me know if you need anything else!

**Comment by Paasu** [comment]
I just installed ADS successfully on my OpenSUSE following the documentation for installation. The issue still exists for Windows but seems to be absent in Linux, if I get the issue again on a Linux system, I'll open up a new issue.

Thank you everyone for helping me with the situation!
