### ISSUE TITLE
DOC: add SOP for when segmentation fails

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#35]
how to correct, what software, etc.

**Comment by alzaia** [comment]
Done in commit 9ba6dd7ac2c1df9ad4c9d4e24327caada3f9e787.

**Comment by jcohenadad** [comment]
the commit reference to the notebook modif is missing. Please add

**Comment by alzaia** [comment]
Commit for the notebook: 42810475481ee0c0bd51b8879879db412cbb37a2

**Comment by jcohenadad** [comment]
reopened because of this:
https://github.com/neuropoly/axondeepseg/commit/42810475481ee0c0bd51b8879879db412cbb37a2#r26452234

from now on: open a specific PR and we will take it from there

**Comment by jcohenadad** [comment]
fixed in https://github.com/neuropoly/axondeepseg/pull/42

**Comment by jcohenadad** [comment]
my bad, i thought that https://github.com/neuropoly/axondeepseg/pull/42 was merged but it is not. Issue is reopened until PR is merged.

**Comment by alzaia** [comment]
Done In #42
