### ISSUE TITLE
Errow with computing morphometric results using FSLeyes

### ISSUE THREAD

**Issue by Paasu** [neuropoly/axondeepseg#350]
**Describe the bug**
I have tried to produce an excel file containing the morphometrics of the TEM images (4008x2672) using FSLeyes but it doesn't work and gives me an error in my terminal. I understand that FSLeyes may not work with Linux, is that the case here? I only have access to Windows and Linux atm. And if so, is there any possible method in which I can obtain an excel file containing the axon number, diameter, myelin thickness, g-ratio, etc?

**To Reproduce**
1. Launch fsleyes
2. Load image
3. Load existing mask
4. Compute morphometrics
5. Specify pixel size and save location
4. See error: [error log.txt](https://github.com/neuropoly/axondeepseg/files/5209650/error.log.txt)
 
**Desktop (please complete the following information):**
 - OS: [OpenSUSE]
 - Version [15.1]
 - Using the latest version of ADS

**Comment by mathieuboudreau** [comment]
Could you go in your terminal and virtual environment, type `pip freeze`, and share the output?

**Comment by Paasu** [comment]
Here you go: [Output.txt](https://github.com/neuropoly/axondeepseg/files/5209974/Output.txt)

**Comment by mariehbourget** [comment]
Hi @Paasu, when specifying the file name and location, can you try to add the extension `.xlsx` to the name of the file?

![Capture](https://user-images.githubusercontent.com/54086142/92946482-bb80c580-f424-11ea-8c02-99406b0a0828.PNG)


I work on Linux to, without the entension in the filename, I have the same error as you, but with the entension, morphomotrics are computed correctly and written to an excel file.

**Comment by mathieuboudreau** [comment]
Thanks for the hint @mariehbourget ! If that is indeed the issue, maybe @Stoyan-I-A could look into if there's a way to give a default file extension to the FSLeyes input box.

**Comment by Paasu** [comment]
Yeah, that fixes the problem. @mariehbourget 

Thanks for the help everyone!

**Comment by jcohenadad** [comment]
Reopening the issue so we could look into a fix to avoid it next time

**Comment by Stoyan-I-A** [comment]
I can add a check to add a default extension if the user has not specified one.

**Comment by Stoyan-I-A** [comment]
Fixed in #358
