### ISSUE TITLE
Good mask example is resampled on RTD

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#354]
We updated our documentation with an example of a good and bad masks for [manual labelling](https://axondeepseg.readthedocs.io/en/latest/documentation.html#guide-for-manual-labelling).

However, because of the resampling on RTD, the good mask example has intermediate values that are not 0, 127 or 255. So the example may not be as clear as we intended.

The image is 375x250 pixels, the resampled size on RTD is 750x500.
We should resize the masks in nearest neighbor to the real size on RTD.

**Comment by jcohenadad** [comment]
Suggestion for replacing the example good/bad mask: include zoomed window, example:

![image](https://user-images.githubusercontent.com/2482071/98268860-04538700-1f5b-11eb-951f-777fff848314.png)
