### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from -r requirements.txt (line 6)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)

### ISSUE THREAD

**Issue by echosvile** [neuropoly/axondeepseg#356]
**i am trying to install wav2lip using anaconda**

**To Reproduce**
1. i ran the pip install -r requirements.txt
2. it was downloading the requirements

(WAV2LIP) C:\Users\user\OneDrive\Documents\WAV\Wav2Lip>pip install -r requirements.txt
Collecting librosa==0.7.0
  Using cached librosa-0.7.0.tar.gz (1.6 MB)
Collecting numpy==1.17.1
  Using cached numpy-1.17.1-cp36-cp36m-win_amd64.whl (12.8 MB)
Collecting opencv-contrib-python==4.2.0.34
  Using cached opencv_contrib_python-4.2.0.34-cp36-cp36m-win_amd64.whl (39.5 MB)
Collecting opencv-python==4.1.0.25
  Downloading opencv_python-4.1.0.25-cp36-cp36m-win_amd64.whl (37.3 MB)
     |████████████████████████████████| 37.3 MB 71 kB/s
Collecting tensorflow==1.12.0
  Downloading tensorflow-1.12.0-cp36-cp36m-win_amd64.whl (45.9 MB)
     |████████████████████████████████| 45.9 MB 1.3 MB/s
ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from -r requirements.txt (line 6)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.1.0 (from -r requirements.txt (line 6))

**Comment by mathieuboudreau** [comment]
Hi @echosvile,

We are not the software developers for Wav2Lip - please post your issue in their repository here:  https://github.com/Rudrabha/Wav2Lip/issues
