### ISSUE TITLE
Error in attempting to use 512 patch size in training

### ISSUE THREAD

**Issue by Paasu** [neuropoly/axondeepseg#360]
**Describe the bug**
#329 suggested using 512 patch size in order to improve accuracy in training, however I come across an issue whenever I try to run the training files after creating 512x512 patches from my images. Image resolution is 4008x2672.
[Error files.zip](https://github.com/neuropoly/axondeepseg/files/5342376/Error.files.zip)
 
**To Reproduce**
1. Adjust patch_size values in dataset_builder.py and training.py from 256 to 512.
2. Run dataset_builder.py
3. Run training.py

**Desktop (please complete the following information):**
 - OS: [OpenSUSE]
 - Version [15.1]
 - Latest version of ADS

**Comment by mariehbourget** [comment]
Hi @Paasu 
The error `ValueError: cannot reshape array of size 65536 into shape (512,512,1)` suggests that the patches read by `training.py` are 256x256 (because 256x256=65536).
Can you confirm that after running `dataset_builder.py`, you have 512x512 patches in your `path_training` folder?

Given the dimensions of your images, the pixel size in micrometer of `0.00166666666` and the general pixel size of `0.0086`, it should split the image in 4 patches of 512x512.

**Comment by Paasu** [comment]
Hey @mariehbourget 
The patches seem to be 512x512, as I checked in the image properties. However, there are 11 patches per image produced.
Here is an example of a patch:
![image_0](https://user-images.githubusercontent.com/50454820/95771468-b47ff800-0ced-11eb-90c6-9c288705c344.png)
Also, in each sample folder I have make sure to include the `pixel_size_micrometer.txt` with the value of `0.0016666666666667`.

**Comment by mariehbourget** [comment]
Hi @Paasu 
Are all 12 patches per image 512x512?
I suspect that the 4 first patches (0 to 3) are 512x512, and that they are mixed with 256x256 patches (4 to 11) from your previous experiment.
Can you try to run dataset_builder again with new destination folder paths for `path_patched_data_train`, `path_patched_data_validation`, `path_final_dataset_train` and `path_final_dataset_validation`.

**Comment by Paasu** [comment]
Hey @mariehbourget 
You were correct, it appears that both 512x512 and 256x256 were in the same folder. I cleared the folder and ran dataset_builder.py again and then the training.py and the training is working fine.

Thanks for helping me out again!
