### ISSUE TITLE
Display issue on RTD with new changelog format

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#367]
The new changelog format used for the 3.2.0 release doesn't display properly on [RTD](https://axondeepseg.readthedocs.io/en/latest/documentation.html#changelog) (version title and links).
It seems that the CHANGELOG.md file which is included in RTD by documentation.rst on line 478 is not rendered as markdown.

**Comment by jcohenadad** [comment]
solution implemented in [sct](https://spinalcordtoolbox.com/en/latest/dev_section/CHANGES.html):
- create a [symlink to the MD changelog file](https://github.com/neuropoly/spinalcordtoolbox/blob/master/documentation/source/dev_section/CHANGES.md)
- point to the symlink in the [index](https://github.com/neuropoly/spinalcordtoolbox/blob/master/documentation/source/index.rst)
