### ISSUE TITLE
TEM data not segmenting well with CLI for multiple images in a folder

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#369]
In the CLI, when pointing on a folder with multiple images, the function `segment_folder` of `AxonDeepSeg/segment.py` is called. 
ex: `axondeepseg -t TEM -i path_image/`
The function contains an old code line to invert contrast for TEM images [here](https://github.com/neuropoly/axondeepseg/blob/d13c0b0a541f139690afdb93ccb38cf92db4682e/AxonDeepSeg/segment.py#L162).

We had this bug earlier and the same code line was removed in PR #294 for the function `segment_image` used with the CLI pointing on a single file.
ex: `axondeepseg -t TEM -i path_image/image.png`

**Comment by mathieuboudreau** [comment]
Good catch! Seems like a quick fix. Do you want me to do it and you review, or vice versa?

**Comment by mariehbourget** [comment]
I'm on vacation tomorrow, so I'll do it now and you can review, if that is ok with you
