### ISSUE TITLE
DOC: how to post-process segmentations.

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#37]
explain step-by-step tutorial with AxonSeg dependency.
Deadline: Dec 31st.

**Comment by alzaia** [comment]
Just to make sure, this refers to the maps generation of metrics? Or the use of AxonSeg to segment for example myelin by using the axon mask of ADS as input?

**Comment by jcohenadad** [comment]
i meant the use of AxonSeg to segment for example myelin by using the axon mask of ADS.
but it seems to be addressed now:
https://neuropoly.github.io/axondeepseg/documentation.html#post-processing-tools
so we can close.
