### ISSUE TITLE
Fsleyes GUI Issue 

### ISSUE THREAD

**Issue by n-amb** [neuropoly/axondeepseg#374]
**Describe the bug**
The bug occurs within FSleyes after selecting the ADScontrol option in the settings drop down menu. An error message appears within FSleyes that reads 'Failed to load image from file..."; the error also lists a path to some folder within Axondeepseg. Attached is a screen capture of the error message. 

In attempt to fix the bug, I re-installed the development version of Axondeepseg into a new conda environment. I then tried to re-install FSleyes, but I received several errors messages (documented in the attached .txt file ). 

**To Reproduce**
Steps to reproduce the FSleyes error message:
1. Open the fsleyes GUI
2. Select the ADScontrol option from the setting drop down menu. 

Steps to reproduce the Re-installation error:
1. Create new conda environment using directions posted within provided documentation
2. Re-install development version of Axondeepseg using directions posted within provided documentation
3. Re-install FSLeyes using directions posted within provided documentation

**Desktop**
- MacOS 
- Version 10.15.7 
- Conda version 4.9.1

FSLeyes error message: 
[Screen Shot 2020-10-27 at 1 51 45 PM](https://user-images.githubusercontent.com/71902782/97492953-7a376d00-1921-11eb-8d73-e41dbe569467.png)

Re-installation error message: 
[error_message_log.txt](https://github.com/neuropoly/axondeepseg/files/5454618/error_message_log.txt)

**Comment by Stoyan-I-A** [comment]
The FSLeyes error message pops up when the plugin searches in the wrong directory (usually because of some installation error).

As for the re-installation error, unfortunately I have never encountered this. So, I am not sure what steps to take to fix it. 
I looked on the internet, and found that could try to clean the Conda environment.

```
conda activate (the name of your environment)
conda uninstall fsleyes      # I am not sure if this will do anything
conda clean --all
```

Then trying to reinstall FSLeyes again

`yes | conda install -c conda-forge fsleyes=0.33.1`

**Comment by mariehbourget** [comment]
Thank you @n-amb  for opening this issue. I have not encountered this issue either in the past, hopefully cleaning the conda environment like @Stoyan-I-A  suggested will get rid of the corrupted files error.

If you still have issue when trying to re-install fsleyes, please provide the extended terminal output of the installation.

@mathieuboudreau, I did a fresh install of fsleyes in a new environment on my station (linux) yesterday and it worked as expected, would you be able to try on Mac to see if we can reproduce the issue?

**Comment by jcohenadad** [comment]
@n-amb have you also re-installed ADS in your new conda environment?  What happens if you run:
```bash
axondeepseg_test
```

**Comment by mariehbourget** [comment]
Hi @n-amb,
Great to hear that the conda issue is resolved!

The error message you now have means that one of the installation steps of AxonDeepSeg may not have been successful.
You can retry the installation with the following steps:
* [ ] Go to your home directory with the command `cd ~`
* [ ] Activate your conda environment
* [ ] If not done already, clone our GitHub repository with the command `git clone https://github.com/neuropoly/axondeepseg.git`
* [ ] Open that downloaded directory using `cd axondeepseg`
* [ ] Pull the latest version with the command `git pull`
* [ ] Install AxonDeepSeg and the additional tools needed to run the software with the command `pip install -e .`
* [ ] Once that's done, run the comprehensive test with the following command: `py.test --cov AxonDeepSeg/ --cov-report term-missing`. This will take a few minutes, all tests should passed. (If some tests fail, please provide a screenshot or copy-paste them.)
* [ ] Open fsleyes with  `fsleyes`

If the issue persist or some tests fail,  it might be best for us to schedule a video call so we can go through the steps with screen sharing and see where the issues with the installation are.

**Comment by n-amb** [comment]
@mariehbourget Thanks, your suggestions solved my issues!
