### ISSUE TITLE
Redirect users to GH Discussion if they have questions

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#427]
Currently, ppl post questions on GH issue.

We would like to give https://github.com/neuropoly/axondeepseg/discussions?discussions_q=category%3A%22Questions+about+using+ADS%22 a try

RTD needs to be updated to make it clear for ppl where to ask questions

**Comment by mathieuboudreau** [comment]
I think updating the issue template so that it informs users of this would go a long way maybe.

**Comment by nekohayo** [comment]
See PR #433 for the featurettes and documentaries.
