### ISSUE TITLE
Remove duplication of docs_source and docs

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#43]
See: https://github.com/neuropoly/axondeepseg/pull/40#discussion_r163621688

**Comment by perone** [comment]
We should host only in ReadTheDocs, everything is automatically and there is no duplication. @alzaia in the paper you re-submitted, which link you used to point for the project ? Just to know which links we should keep.

**Comment by alzaia** [comment]
I put the following link: https://neuropoly.github.io/axondeepseg/.

**Comment by jcohenadad** [comment]
once this issue is addressed, please also update the wiki:
https://github.com/neuropoly/axondeepseg/wiki/How-to-update-the-documentation-(sphinx)

**Comment by perone** [comment]
After you merge all changes in the `/docs` folder, I'll submit another PR to add an automatic forward from this link at Github (neuropoly.github.io) to the automatically rendered in ReadTheDocs. So when someone clicks in the paper, it will be automatically forwarded to the ReadTheDocs, so we don't have to update the `/docs` folder everytime we update the docs.
