### ISSUE TITLE
FSLeyes: Implement Ellipse Minor Axis

### ISSUE THREAD

**Issue by vasudev-sharma** [neuropoly/axondeepseg#432]
Once PR #399 is merged, we wish to implement the ellipse minor axis on our ADS FSLeyes plugin. The purpose of this issue to initiate discussions on how do we wish to display the choice of axon shape to our users(  whether they wish to consider the shape of axons as an `ellipse` or `circle`).

**Screenshot of the ADSControl, so we can easily reference to it while brainstorming the design choices of axon shape.**

![image](https://user-images.githubusercontent.com/31419210/103007252-1617da80-4559-11eb-969f-329c118d4084.png)

Any suggestions/feebacks are welcome. 

Here are some of my suggestions:- 

1. Similar to the `Select the modality` dropdown, we can add a dropdown/radio button ( `Select the axon shape` where 2 options would be - `ellipse`  and `circle`) in the ADSControl just before the **`Compute Morphometrics`** button.
2. Second option that I thought of was once an user clicks **`Compute Morphometrics`** button, we can ask to input the axon shape ( the input can be either be a dropdown or radio button, similar to option 1)

**Comment by jcohenadad** [comment]
> Similar to the Select the modality dropdown, we can add a dropdown/radio button ( Select the axon shape where 2 options would be - ellipse and circle) in the ADSControl just before the Compute Morphometrics button.

I like this option better, and we should have a default option already selected. With time, we will have more and more customization, and I would like to avoid having the user click 30 times before getting the results. Everything default that the user wants to keep default should "click-avoidable"

**Comment by Stoyan-I-A** [comment]
I could implement this as soon as #399 is ready for review!
