### ISSUE TITLE
Testing: Inconsistent naming convention of test images and the unit tests

### ISSUE THREAD

**Issue by vs74** [neuropoly/axondeepseg#439]
When AxonDeepSeg segments an image, let say `test.png`, 3 segmented images are generated namely:
1. `test_seg-axon.png` (segmented axon mask)
2. `test_seg-myelin.png` (segmented myelin mask)
3. `test_seg-axonmyelin.png` (segmented axon myelin mask)

where the generated name of the image has a fixed prefix, which is the name of the image, here `test`
and the suffix is concatenated to the segmented mask such as axon mask, myelin mask, and axon myelin mask  as follows: `_seg_axon.png`, `_seg-myelin.png`, and `_seg-axonmyelin.png`

However, in the test files (upload on OSF), the segmented images (let's say under the `test/__test__files/__test__demo__files` directory and also elsewhere) the axon mask, myelin mask and myelin axon mask are named as `AxonDeepSeg_seg-axon.png`, `AxonDeepSeg_seg-myelin.png` and `AxonDeepSeg-axonmyelin.png`, where the image name is not `AxonDeepSeg` but instead is `image.png`. Also, in some of our units test, this same naming convention is followed. See [here](https://github.com/neuropoly/axondeepseg/blob/28666b8be47889df24b6839cefd247e06de16102/test/morphometrics/test_compute_morphometrics.py#L28-L33). This creates a mismatch of naming convention.

I suggest we fix this behavior because: - 
1. We should maintain a common naming convention across our codebase.
2. My PR #434 follows the naming convention similar to the names of the images segmented by ADS and not the naming convention we have in our test files and some unit tests. So, to add tests in my PR, I need this to be fixed so that my tests can pass.

**Comment by mariehbourget** [comment]
Yes, I agree with @vs74, we should have a common naming convention.
In addition to the mismatch with test files, ADS has 3 different behaviors for naming, depending on how the segmentation is performed:

**Notebooks:**
With `axonsegmentation` function from `apply_model.py`, the default value `AxonDeepSeg.png` is used for the `segmentations_filenames` parameter [here](https://github.com/neuropoly/axondeepseg/blob/e2cd6fcc7502db6241cbea4b7b47e1201599315d/AxonDeepSeg/apply_model.py#L188). Resulting filenames are:
1. `AxonDeepSeg.png`
2. `AxonDeepSeg_seg-axon.png`
3. `AxonDeepSeg_seg-myelin.png`

**CLI:**
With `segment_image` and `segment_folders` in `segment.py`,  the default value `img_name_original + '_seg-axonmyelin' + '.png'` is passed to `axon_segmentation` for the `segmentations_filenames` parameter [here](https://github.com/neuropoly/axondeepseg/blob/e2cd6fcc7502db6241cbea4b7b47e1201599315d/AxonDeepSeg/segment.py#L79).
Resulting filenames are:
1. `img_name_original_seg-axonmyelin.png`
2. `img_name_original_seg-axon.png`
3. `img_name_original_seg-myelin.png`

**FSLeyes:**
Output filenames are set [here](https://github.com/neuropoly/axondeepseg/blob/e2cd6fcc7502db6241cbea4b7b47e1201599315d/ads_plugin.py#L437) to: 
1. `ADS_seg.png`
2. `ADS_seg-axon.png`
3. `ADS_seg-myelin.png`

As Vasudev, I prefer the the **CLI** naming.
It is also compatible with the naming convention for segmentation in ivadomed.

**Comment by mathieuboudreau** [comment]
Sorry for the mismatch ini unit tests, that's on me. I think I was just replicating whatever convention we were using ini the code 3 years ago, before the project got a bit more organised in terms of conventions. I'm fine with whatever convention we pick, and we should centralise it either code or the wiki.

**Comment by vs74** [comment]
@mariehbourget I wasn't aware of different naming conventions followed in our **Notebooks** and in **FSLeyes**, thanks for bringing this out. 

>pick, and we should centralise it either code or the wiki.

Not to forget the test files on OSF too.

**Comment by mathieuboudreau** [comment]
Yes, I meant after we change all the names, we should have either a centralised place to store the convention or inform developers.
