### ISSUE TITLE
Question: significance of script `set_config.py`? 

### ISSUE THREAD

**Issue by vs74** [neuropoly/axondeepseg#447]
Following the discussion in PR #441 regarding centralizing the suffixes' names into a single location, I thought of creating a config.py file where the hardcoded values will be stored and used by the developers whenever they need.

However, there is already a script named [set_config.py](https://github.com/neuropoly/axondeepseg/blob/master/set_config.py) in AxonDeepSeg which is not used anywhere in the project. This script contains paths of **axonseg** and **MATLAB**. May I know why in the first place this script was created? From what I can understand, it has something to do with **axonseg**, but I am not sure the exact purpose of it.

**Comment by jcohenadad** [comment]
good catch-- maybe @alzaia has a clue?

**Comment by alzaia** [comment]
This was probably an earlier script from the very first version of ADS, when we were planning to do only the axon segmentation by deep learning and then do the myelin segmentation via the AxonSeg code.

**Comment by vs74** [comment]
Thank you @alzaia for the update. As reported by @alzaia that [set_config.py](https://github.com/neuropoly/axondeepseg/blob/master/set_config.py) was used earlier, but not needed right now since we can do axon and myelin segmentation using deep learning. Hence, we should remove this old config file for two reasons. 

1. First, in PR #441, I've added an additional config file [config.py](https://github.com/vs74/axondeepseg/blob/vs/fix_naming_convention/config.py) which contains the hardcoded strings used in ADS. So, for the developers of ADS it would create confusion if there are 2 config files in the first place. 

      The config files are a) an old config file -- [ set_config.py](https://github.com/neuropoly/axondeepseg/blob/master/set_config.py) (which is not used anymore)  and b) new config file -- [config.py](https://github.com/vs74/axondeepseg/blob/vs/fix_naming_convention/config.py) (from PR #441 which will eventually get merged in the master branch)

2. Second, the old config file [ set_config.py](https://github.com/neuropoly/axondeepseg/blob/master/set_config.py) is obsolete as it is not being used in the codebase. So we should remove the old config file. In case, if in the future we do require the old config file ([ set_config.py](https://github.com/neuropoly/axondeepseg/blob/master/set_config.py), we could refer to the Git history.


I'll create a PR for the same.
