### ISSUE TITLE
FSLeyes: Add option to adjust overlap value

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#451]
The overlap value for segmentation in FSLeyes is currently hardcoded to 25 [here](https://github.com/neuropoly/axondeepseg/blob/5af8cbb1e782092ac46e0586eca0f827c0eff938/ads_plugin.py#L352).

We would need an option for the user to choose a different value. For example, with peripheral nerves segmentation, better results are obtained with an overlap value of 50.
Related to #385

**Comment by Stoyan-I-A** [comment]
I'm thinking of adding a sort of "Settings menu" where the user will be able to teak this and other parameters such as the file names (related to https://github.com/neuropoly/axondeepseg/issues/445). I will discuss it in our next meeting.

**Comment by Stoyan-I-A** [comment]
This was implemented in #458
