### ISSUE TITLE
Add a settings menu to the plugin

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#458]
PR #462

I propose adding a settings menu to the FSLeyes GUI.
In this menu, the user could:
- Change some values that were previously hardcoded (exemple: https://github.com/neuropoly/axondeepseg/issues/451)
- Change the suffix we look for when loading a mask. Currently, we only support loading masks that contain both axon and myelin in the image. A given suffix would determine if a certain image contains only axon or myelin.
- Determine if we use the ellipse or circle for computing morphometrics
- Check the pixel size of the selected image

Feel free to add any other suggestions

**Comment by mariehbourget** [comment]
We may need to have a pixel size field and be able to change the value between segmentation and morphometrics. See comment [here](https://github.com/neuropoly/axondeepseg/discussions/450#discussioncomment-374733).

**Comment by mathieuboudreau** [comment]
I think we should likely just have one true pixel size value for the user to input, and then another "zoom" parameter for the segmentation patch step? Morphometrics will always use the true pixel size value, and the zoom factor * pixel size would be used in the segmentation stage. Thoughts?

**Comment by mariehbourget** [comment]
That's a good idea, I like it! Only one true pixel size is less confusing, will avoid errors and is compatible with having a pixel_in_micrometer.txt file as well. Thanks @mathieuboudreau!

**Comment by Stoyan-I-A** [comment]
I started working the settings menu. Here's what it looks like so far:
![image](https://user-images.githubusercontent.com/43790661/108615629-1f47eb00-73d4-11eb-98c9-54153c9aff22.png)

**Comment by jcohenadad** [comment]
maybe next to "overlap value" you can add "(%)"

**Comment by jcohenadad** [comment]
and i would replace "axon shape" by "axon shape approximation"

**Comment by jcohenadad** [comment]
also, would it be possible to have all buttons with the same size? it would look more professional

**Comment by Stoyan-I-A** [comment]
> also, would it be possible to have all buttons with the same size? it would look more professional

I will explore what options are available. Also, they don't have this appearance on macOS.

**Comment by mariehbourget** [comment]
> maybe next to "overlap value" you can add "(%)"

the overlap value is in "(pixels)"

**Comment by jcohenadad** [comment]
> > maybe next to "overlap value" you can add "(%)"
> 
> the overlap value is in "(pixels)"

ah! so that's a good reason for specifying "pixel" then 😉  (otherwise users might think it is in %)

**Comment by jcohenadad** [comment]
> > also, would it be possible to have all buttons with the same size? it would look more professional
> 
> I will explore what options are available. Also, they don't have this appearance on macOS.

could be ported to another issue if we want to fix the other things quicker (this is not priority)

**Comment by Stoyan-I-A** [comment]
![image](https://user-images.githubusercontent.com/43790661/109579735-7b42fb80-7ac7-11eb-9969-a58cd885ae18.png)
Updated settings menu.

- The model resolution setting has been added to deal with #428 . The downside is it will have to be modified even if we use our default models.
- The Axon shape setting has been removed until #399 is merged.
- A checkbox to use a custom image resolution has been added. If it's checked, the aquired resolution specified in the box will be used instead of the one found in the `pixel_size_in_micrometer.txt` file.
- There's currently an issue where the variables aren't updated right away when changing the value in the settings menu. If you press the enter key after changing a value, it should work correctly (I temporary added prints in the console when the variables are updated to make sure I don't try to apply a model with incorrect values).
- I don't really like the way I structured the code at the moment. I feel like the settings variables and the functions that handle the settings menu should be in a new class and not in the same one as the rest of the GUI.

**Comment by mariehbourget** [comment]
Hi @Stoyan-I-A!
I think there may be a misunderstanding between `model resolution`, `pixel size` and `zoom factor`.

In the last meeting, we decided to integrate the peripheral nerves model as a new “default” model in ADS. This was done by Vasudev in PR #457. It includes a hardcoding of the model resolution of 0.1 [here](https://github.com/vs74/axondeepseg/blob/8e994679e6866d0dc2d37b5e95ceaad2179e9012/AxonDeepSeg/segment.py#L236).

This means that for now, we do not want to include the custom model resolution option in FSLeyes (#334) or CLI (#428), but only add a third default model option.

As a priority for Simeon, we need to be able to select the `overlap_value` and a `zoom factor` (see [comment](https://github.com/neuropoly/axondeepseg/issues/458#issuecomment-780575113) above) to apply to the pixel size.

The idea is:
- There is only 1 true `pixel size` (either in the txt file or set by the use in FSLeyes). This pixel size is the real pixel size of the image and must be used to compute morphometrics.
- A second parameter `zoom factor` can be applied to multiply the `pixel size` to improve the results of the segmentation only (not applied to morphometrics).
- The `model resolution` always remains the same and should be hardcoded at `0.1`.

Example:
```
pixel size = 0.1
zoom factor = 0.8
pixel size applied for segmentation = pixel size * zoom factor = 0.1 * 0.8 = 0.08
pixel size applied for morphometrics = 0.1
```

Let me know if that makes sense, or if you want to chat about this.

**Comment by Stoyan-I-A** [comment]
Alright, here's the updated one as of 2021-03-06:
![image](https://user-images.githubusercontent.com/43790661/110225370-1f0b1d80-7eb3-11eb-95e0-9492d461b30a.png)

**Comment by mathieuboudreau** [comment]
@Stoyan-I-A I think this issue was closed automatically when closing the PR, which was approved by @mariehbourget, however I saw in the meeting minutes from this week that you may not have been satisfied with the code and that it may need refactoring. I recommend you open a new issue for that if you plan on pursuing it.
