### ISSUE TITLE
Consider revisiting -o flag, which sounds like "output"

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#460]
Currently, we use "-o" for "overlap", but intuitively it means "output". We should revisit this flag.

**Comment by vs74** [comment]
I agree, perhaps we could use the `--overlap` flag instead of `-o `flag.

**Comment by mariehbourget** [comment]
I agree with `-overlap`. Alternatively, I think `-ov` would do the trick if we want a shorter version.

**Comment by jcohenadad** [comment]
> Alternatively, I think -ov would do the trick if we want a shorter version.

from UX perspective, i tend to prefer things that are explicit. Putting myself in the shoes of newbies, it is reassuring to see flag options that we intuitively understand from their names, instead of being "forced" to read the description of all the flags to understand what each does
