### ISSUE TITLE
Shall we switch to PR template for ADS?

### ISSUE THREAD

**Issue by vs74** [neuropoly/axondeepseg#466]
PR templates are used in the sister projects [SCT](https://github.com/neuropoly/spinalcordtoolbox) [(example PR)](https://github.com/neuropoly/spinalcordtoolbox/pull/3246) and [Shimming-Toolbox](https://github.com/shimming-toolbox/shimming-toolbox) [(example PR)](https://github.com/shimming-toolbox/shimming-toolbox/pull/232) .

I kind of liked the idea of using the template PR for two main reasons.
1. Ensures that the dev's/contributors address specific checklists.
2. Easy for the reviewers to review the PR.

I'm interested in knowing whether should we also switch to a PR template?

**PS:** Also, oftentimes we merge the PR without adding relevant labels to the PR, so adding a PR template would ensure these kinds of bad practices are not followed.

**Comment by ahill187** [comment]
Great idea!

**Comment by mathieuboudreau** [comment]
Agreed, I'm ok with testing this to see if it's worth it.
