### ISSUE TITLE
Unit test Failing for test_score_analyses_runs_successfully_with_visualization_on

### ISSUE THREAD

**Issue by dyt811** [neuropoly/axondeepseg#478]
**Describe the bug**

* Unit test failing.. during tear down. 

**To Reproduce**

1. on Windows platform
1. Create new conda envionrment using the environment.yml 
1. Run quick test: test should pass. 
2. Run pytest full
3. Unit test fails at clean up process for C:\git\axondeepseg\test\testing\test_segmentation_scoring.py:77:

* See detailed stack trace in log file attached. [CMDConsoleLog.log](https://github.com/neuropoly/axondeepseg/files/6176781/CMDConsoleLog.log)
* Reproduced in 2 Windows10 PCs, with or without nvidia GPU. 
* Reproduced in experimental GitHub Action Pytest

**Platform (please complete the following information):**
 - OS: Windows [Version 10.0.19042.867]
 - AxonDeepSeg version number: Master branch as of 2021-03-20T232341EST for 837562b4c1e343dcc80a7bb7a12d44e299977481

**Comment by dyt811** [comment]
Updated reference to the experimental GitHub Action Unit Testing branch where this failed:

- [Failures line from PyTest](https://github.com/MotionCorrect/axondeepseg/runs/2158090993?check_suite_focus=true#step:10:260)
- [Exit code 1 from PyTest](https://github.com/MotionCorrect/axondeepseg/runs/2158090993?check_suite_focus=true#step:10:1292)

**Comment by dyt811** [comment]
Confirmed it is a Windows ONLY issue. Similar tests past in both Ubuntu and macOS.

**Comment by dyt811** [comment]
Root cause identified and resolved as an indent is needed at [Line79](https://github.com/neuropoly/axondeepseg/blob/master/test/testing/test_segmentation_scoring.py#L79) for Windows to properly close the "with" clause.

This will be bundled with the upcoming TravisCI fix, which require addressing this to pass.

**Comment by mathieuboudreau** [comment]
Thanks for finding this and resolving it @dyt811 ! Yeah, I recall encountering some really annoying permissions errors while trying to create/delete temp files in python for this project earlier on and thought I had resolved them all, but we've not touched on Windows for a long time now.
