### ISSUE TITLE
Avoid  Wildcard imports (`import from *`) in scripts

### ISSUE THREAD

**Issue by vs74** [neuropoly/axondeepseg#486]
In ADS, there are certain scripts where wildcard importing is used. Look at [compute_morphometrics.py ](https://github.com/neuropoly/axondeepseg/blob/b3c7fb928b20e63533803a050511f483f502e998/AxonDeepSeg/morphometrics/compute_morphometrics.py#L18)script,[ launch_morphometrics.py](https://github.com/neuropoly/axondeepseg/blob/b3c7fb928b20e63533803a050511f483f502e998/AxonDeepSeg/morphometrics/launch_morphometrics_computation.py#L9) script, [test_performance_metrics.py](https://github.com/neuropoly/axondeepseg/blob/b3c7fb928b20e63533803a050511f483f502e998/AxonDeepSeg/testing/launch_performance_metrics.py#L4) script, [noise_simulation.py](https://github.com/neuropoly/axondeepseg/blob/b3c7fb928b20e63533803a050511f483f502e998/AxonDeepSeg/testing/noise_simulation.py#L13) script and many others..

We should avoid using wildcard import probably because : -

1. It is inefficient as large number of objects are imported while doing wildcard imports.
2. One doesn't know the origin of variable / class  or method while debugging or implementing code in these scripts.
3. It adds on namespace collisions.

**Comment by mathieuboudreau** [comment]
I just checked the `blame` feature on GitHub for those instances, 3 out of 4 of them are from 3+ years ago prior to my arrival, and the other is from one external contributor, so I think that means internally that's not been a problem for this project. Feel free to create a PR to correct these if you have the change.
