### ISSUE TITLE
Cannot find path to a font file cause crash in generate_axon_numbers_image when utilizing matplotlib 3.4.0

### ISSUE THREAD

**Issue by dyt811** [neuropoly/axondeepseg#488]
**Describe the bug**

- Unit test test_generate_axon_numbers_image_returns_expected_array is failing only on Windows environment. 
- Introduced in the latest master branch PRs somehow (as previous PR was passing while working on PR #479 ? Super strange. Glad GitHub action caught it here though
- It is VERY likely related to windows path vs ubuntu path. Still investigating root cause. 

**To Reproduce**

1. Install new conda env based on environment.yml
2. pip install -e .
2. run pytest for test\test_postprocessing.py

**Platform (please complete the following information):**
 - OS: Windows 10. Reproduced both in GitHub Action as well as locally on my Win 10 laptop. 
 - AxonDeepSeg: Master

Pytest output captured log: 
[2021-03-27T001508EST_pytest_failure.log](https://github.com/neuropoly/axondeepseg/files/6215112/2021-03-27T001508EST_pytest_failure.log)

Going to try to incorporate this as part of PR #479 since that will be the first place flagging this issue.

**Comment by dyt811** [comment]
Root cause identified. it was caused by an outside library exhibiting behaviour different on Ubuntu vs Windows. The font path was giving an issue. Somehow, Windows version of the matplotlib does not contain a "datapath" key to a font... which is used in generate_axon_numbers_image. 🤷 

See below. Bizarre.

![2021-03-27T002942EST_Debug](https://user-images.githubusercontent.com/6720068/112709960-04194100-8e94-11eb-9bfa-4eb47dd6cc73.png)

⢀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⣠⣤⣶⣶
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⢰⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣀⣀⣾⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡏⠉⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿
⣿⣿⣿⣿⣿⣿⠀⠀⠀⠈⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠉⠁⠀⣿
⣿⣿⣿⣿⣿⣿⣧⡀⠀⠀⠀⠀⠙⠿⠿⠿⠻⠿⠿⠟⠿⠛⠉⠀⠀⠀⠀⠀⣸⣿
⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⣴⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⢰⣹⡆⠀⠀⠀⠀⠀⠀⣭⣷⠀⠀⠀⠸⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠈⠉⠀⠀⠤⠄⠀⠀⠀⠉⠁⠀⠀⠀⠀⢿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⢾⣿⣷⠀⠀⠀⠀⡠⠤⢄⠀⠀⠀⠠⣿⣿⣷⠀⢸⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⡀⠉⠀⠀⠀⠀⠀⢄⠀⢀⠀⠀⠀⠀⠉⠉⠁⠀⠀⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿

**Comment by dyt811** [comment]
Further digging into GitHub CI actions suggest 

Matplotlib 3.3.4 to 3.4 WILL likely break everything... across platform for this part. 

Right now, only Windows has 3.4 and we were not locking down the dependencies.. to ~=3.3.4

![image](https://user-images.githubusercontent.com/6720068/112710168-87876200-8e95-11eb-95c0-7d607d29470b.png)

![image](https://user-images.githubusercontent.com/6720068/112710223-d92fec80-8e95-11eb-969f-4d1c393bf553.png)

So the lessons learned are: 

1) Why it is important to do cross platform build like this in CI to catch esoteric issues like this....
2) Some platform has dependencies updated faster... because. Matrix testing with many combo... etc is the only sure way to know what works and what doesn't. 
3) Need to lock down subversion number in conda/pip
3) Why looking forward to future version might potentially help scenarios similar to this. 
4) We might start considering a better way to deploy the path

Remedial action to be issued in PR #479:
- lock down the specific version of matplotlib
- Open separate issue documenting this quirky behavior to get font file for display purposes so it can be addressed in the near future adapting the way the matplot lib rc parameters are keyed in the rc dictionary

**Comment by mathieuboudreau** [comment]
> So the lessons learned are:
> 
> 1. Why it is important to do cross platform build like this in CI to catch esoteric issues like this....

Thanks for discovering this @dyt811 and investigating this. We weren't testing for windows before because 1) Travis didn't allow for it, and 2) because we had internally voted against supporting for Windows after a short while of supporting it, because it's such a PITA in my experience for cross platform compatibility in this project. We only recently decided to support it again, although as I mentionned to @jcohenadad in our last group meeting, if these types of issues come up frequently it's my view that we should just drop Windows again and ask people to us a VM if they want to use it in Windows, because our time should not overwhelmingly be spent debugging stuff just because it breaks on Windows for x,y,z reasons.

**Comment by Stoyan-I-A** [comment]
> We might start considering a better way than depending on rcParameters from matplotlib. Relying on highly specific parameters this way is fragile.

Perhaps this could help: https://matplotlib.org/stable/api/font_manager_api.html
There's a `findfont` function.
```
I tried this on Windows:
>>> matplotlib.font_manager.findfont("DejaVu Sans")
'C:\\Users\\Stoyan\\PycharmProjects\\general_testing\\venv\\lib\\site-packages\\matplotlib\\mpl-data\\fonts\\ttf\\DejaVuSans.ttf'
```
This would be a better way to fix the issue and it would still work whenever we upgrade to matplotlib >= 3.4.0

**Comment by dyt811** [comment]
> Thanks for discovering this @dyt811 and investigating this. We weren't testing for windows before because 1) Travis didn't allow for it, and 2) because we had internally voted against supporting for Windows after a short while of supporting it, because it's such a PITA in my experience for cross platform compatibility in this project. We only recently decided to support it again, although as I mentionned to @jcohenadad in our last group meeting, if these types of issues come up frequently it's my view that we should just drop Windows again and ask people to us a VM if they want to use it in Windows, because our time should not overwhelmingly be spent debugging stuff just because it breaks on Windows for x,y,z reasons.

Yeah, good point. I totally understand there are significant hurdles when it comes to support windows especially if some external dependencies behaves oddly across platforms.  My perspective on this is, we should still at least include unit test (even marking them optional for PR) when we have access to Windows CI facilities so at least people are aware of occasional limitation and like you said, focus on the Ubuntu/Linux base as bulk of the especially large scale computing are happening there. 

Fortunately, this issue was more related to dependency misbehaving than others but I completely agree that should future OS specific issues arises, Ubuntu/Linux will always be prioritized in terms of developer resources than other OS.
