### ISSUE TITLE
Improve workflow

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#49]
Currently, ADS requires images prepared in a certain way, which makes it difficult for other researchers to run the software properly. 
Since these preprocessing steps are easy to integrate within ADS, it should be done there, instead of manually by the user. Preprocessing includes:

- [ ] File input management: add a module that checks the input data and convert it to png if required.
- [ ] Contrast adjustment: depending on the modality (SEM or TEM), change image contrast appropriately. For SEM: `img = imageio.imread(filename)`. For TEM: `imageio.imwrite(filename,255 - img)`

**Comment by alzaia** [comment]
This was addressed in PR #50
