### ISSUE TITLE
FSLeyes video tutorial has disappeared from RTD

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#492]
I just notice that the video tutorial for FSLeyes is no longer in RTD.

Based on the rendered version of the docs in recent PRs, the link to the tutorial was present in PR #474 merged 13 days ago, but not in PR #476 merged 7 days ago.

I'm not sure what happened here because PR #476 did not change the `documentation.rst` file and I can't find PRs that were merged between those two.
Any ideas?

**Comment by vs74** [comment]
In between these PR's there is PR #452, where the documentation was updated by @mathieuboudreau ( see this [commit](https://github.com/neuropoly/axondeepseg/pull/452/commits/7c049c6ac41fa76d6877ff92d870270aa1c93077))

**Comment by mariehbourget** [comment]
Thanks @vs74 , I totally missed it when reviewing PR #452. I'll open a new PR to add the tutorial back to the doc.
