### ISSUE TITLE
Brainstorm about an improved way to generate numbers

### ISSUE THREAD

**Issue by vasudev-sharma** [neuropoly/axondeepseg#512]
Following minutes of meeting with Alan, I found that we need to find a better way to generate the numbers in FSLeyes.

I am quoting the notes taken from the meeting below,

```
- have a way to generate them outside of FSLeyes
- increase the size of the numbers, or find another way to generate them. Eg: output image with/without the numbers. 
```

It would be nice if some context can be provided about the issue and we can start discussing this, hence I opened this issue to keep the discussion get started.

**Comment by mathieuboudreau** [comment]
What numbers are we talking about in this issue?

**Comment by mathieuboudreau** [comment]
The overlays identifying the axon ID?

**Comment by vs74** [comment]
I guess the numbers are the overlaid numbering identifying each of the myelin/axon instances in the FSLeyes plugin.

Since I wasn't part of the meeting, perhaps @mariehbourget or @Stoyan-I-A or @jcohenadad can provide a better context about the notes taken and this issue.

**Comment by mariehbourget** [comment]
They are unfamiliar with the software and were asking clarifications based on screenshots we send them.
Their main concern was that yellow numbers against a gray background were difficult to read, and numbers were small compared to the screenshots size. This can all be fixed by zooming in the GUI and changing the color of the numbers.

However, they asked if we could generate the numbers and saved them in overlay in a file outside the GUI.
I don't recall why we would need to review the size though.

**Comment by Stoyan-I-A** [comment]
If we want to generate the layer of numbers, we can just use [the same function used in the GUI](https://github.com/neuropoly/axondeepseg/blob/e32dcfc582ab9cb0b886af57aa9075a95cf958ee/AxonDeepSeg/postprocessing.py#L97).
If we want to change the size of the numbers, the last parameter can be adjusted.
If we want to export the numbers layer as a colored image, we can use [this function](https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#PIL.ImageOps.colorize) from the Pillow package.

I could add an example in a notebook if it can help.

**Comment by jcohenadad** [comment]
Discussed with @mariehbourget-- great initiative, we should open a PR and replace the number feature from FSLeyes plugin by this new CLI numbering output (ie: FSLeyes will load the numbered axons).

**Comment by mariehbourget** [comment]
> Discussed with @mariehbourget-- great initiative, we should open a PR and replace the number feature from FSLeyes plugin by this new CLI numbering output (ie: FSLeyes will load the numbered axons).

Just a precision: based on the previous comment from Stoyan, @vs74 and I worked on a quick implementation of a `_numbers.seg.png` file to include with the results when running the morphometrics in CLI for Alan's project.
The plan would be to open a PR about this to include the feature in ADS both when running the CLI and when computing morphometrics from fsleyes.

**Comment by Stoyan-I-A** [comment]
So essentially a `_numbers_seg.png` file would be generated when the morphometrics are computed, is that correct?
For the FSLeyes plugin, we would just load this new file afterwards.

**Comment by Stoyan-I-A** [comment]
I made the changes in #519. Check it out whenever you'll have some time.
