### ISSUE TITLE
Add support for generating morphometrics files when images present in the same directory

### ISSUE THREAD

**Issue by vasudev-sharma** [neuropoly/axondeepseg#514]
Currently, the recently merged PR (https://github.com/neuropoly/axondeepseg/pull/434), which adds an additional CLI feature to generate morphometrics files of the image using CLI command, is missing an additional functionality where  when a user wants to generate morphometrics of all the images present in the same directory, the **axondeepseg_morphometrics** cli doesn't work for this use case.

## **Proposed Solution**
For this, instead of just naming the the morphometrics files as `axon_morphometrics.xlsx`, I suggest we prepend the image name too with the computed morphometrics files. For instance, if the image name is` test_image.png`, the moprhometrics file generated would be `test_image_axon_morphometrics.xlsx` Renaming the morphometrics file would add an additional support for the described use case, where all the images are present in the same directory.

I'll open a PR resolving this issue.

**Comment by mathieuboudreau** [comment]
We should maybe give other options. Some people might just one single excel file for all morphometrics, while other people might one one excel file but with tabs for each image.

**Comment by vs74** [comment]
That's really a nice suggestion. Perhaps we could these options 
1. Single excel file for all the morphometrics (as suggested by @mathieuboudreau )
2. Individual excel files for each of the images (as I suggested)
3. A single file where each tab for each image (as suggested by @mathieuboudreau )

Options 2 and 3 are almost identical; we need to have a consensus on which we should go forward with. I prefer @mathieuboudreau 's option, that is option 3

Also, @mathieuboudreau when you say a single excel file for all the morphometrics, may I know what do you mean? Can you elaborate a little?

**Comment by jcohenadad** [comment]
hello! sorry i'm late to the party 😬 

i'm 100% in favour of option 2, ie: using image file name and add suffix "_ads_morphometrics.csv"

i don't recommend option 3: we definitely don't want to spend development time on playing with Excel tabs. Moreover, we want to push people to use CSV instead.

**Comment by vs74** [comment]
Opened PR #518 for this. 

> i'm 100% in favour of option 2, ie: using image file name and add suffix "_ads_morphometrics.csv"


@jcohenadad as discussed earlier we decided to add suffix `_axon_morphometrics.csv` to the morphometrics file. Would you like to change it to `_ads_morphometrics.csv` instead?

**Comment by jcohenadad** [comment]
>  Would you like to change it to _ads_morphometrics.csv instead?

only if everyone is ok with that

**Comment by mariehbourget** [comment]
> > Would you like to change it to _ads_morphometrics.csv instead?
> 
> only if everyone is ok with that

I don't have a strong opinion about this, both are good with me.
