### ISSUE TITLE
AxonDeepSeg v4

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#523]
@mariehbourget, @vasudev-sharma, and I just met to get the discussion started on thoughts/strategy for the version 4 release of AxonDeepSeg, which will be a major refactor that will use IVADOMED. Feel free to edit or write questions below.

## Preliminary work
* Reseach IVADOMED/ADS overlap/differences
  * Make a two-column table that lists/identifies ADS functions with their equivalent IVADOMED functions
    * [GDoc File](https://docs.google.com/document/d/1Ipd6_nK6I6CKlDI_KpkLXH_jY2C547W_ootalfKnFlU/edit?usp=sharing) 
* Leave ADS’s API as unchanged as possible
* List all main ADS user entrypoints & options
  * Command line
  * FSLeyes
  * Jupyter Notebook
* Tests
  * Identify tests that will have to be completely deleted (entire functionality is replaced by IVADOMED)
  * Identify tests that should be untouched (API, or files that have no overlap with IVADOMED).
  * Identify tests that will need to be modified for them to work with the new ADS version.
* Models/Segmentations
  * Create models using IVADOMED for all of our current models

## Repository

* Create a new branch (v4) that will be the “master branch” of all these changes, and will be what is merged for release
* Ramp down PRs on our current master branch
  * Only essential PRs should be merged or worked on (e.g. collaborations, bugs)
  * Ideally, these would also be merged somewhere too in our v4 tree (or worked on), if compatible.

## Task flow

* First identify all the API that will need to be untouched, meaning that we might need to keep some functions that wrap around other code or calls IVADOMED?
* Delete files and functions that have overlap with IVADOMED but not required for our API (delete their tests too).
  * See if any of the remaining test fail after this step, and plan accordinlgy
* Refactor files that have overlap with ivadomed, but are required for our API.
  * Ensure tests pass with minimal changes to them.
* Test all our API entrypoints, and fix our refactored code accordingly
* Compare our old models with our new models; ensure approximately equivalent quality of segmentations on test images.
  * Report the differences, or recommend improvements to IVADOMED code.

## New features?
* BIDS-app for segmentation?
* Git-annex bidsified datasets?

**Comment by mariehbourget** [comment]
As references:

**Models:**
I put an example of model from `ivadomed` here: https://drive.google.com/drive/folders/1vOc-HazqyE4xeyBWwbl4OTpoCcEhafad. There are 3 files:

- json config file of the model
- onnx model file (this is generally the format of saved ivadomed's model)
- pt model file (in some cases, model are saved as pt file when features are not compatible with onnx)

**sct_deepseg:**
- Here is a link to the `sct_deepseg` script which use the command `segment_volume` from `ivadomed` to segment images in `SCT`. This is the same entry point (`segment_volume`) that we would want to use with `ADS`: https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/spinalcordtoolbox/scripts/sct_deepseg.py
- `segment_volume` is called [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a0b02cb485b54d89e6942c232b7f20a30e6b8353/spinalcordtoolbox/scripts/sct_deepseg.py#L207) with the path of the model, a list of filenames to segment and options.
- In our case, options will be:
    1. PixelSize, preferably as a 2D array ex: [0.1, 0.1]
    2. overlap_value, format is not fully determined at the moment, probably also a 2D array since overlap can be different on each axis.

**segmentation output from ivadomed:**
I have yet to implement this part, but my plan is to provide 2 output segmentations in the same file format as the ground truth (e.g: png, tif or jpg), one segmentation mask for myelin and one segmentation mask for axon.

**Comment by mariehbourget** [comment]
The microscopy pipeline is completed in ivadomed.

**Model:**
I have put a new temporary SEM model on drive [here](https://drive.google.com/drive/folders/1qUPvlmmZiqLyKqTlAXATpL4QSWC3HsnZ).
It contains the model config file (`json`) used for training and 2 files (`onnx` and `pt`) of the model itself.

**Segmentation:**
The segmentation from ADS will be a 2-steps process, both functions from `ivadomed/inference.py`. (similar to example of sct_deepseg in previous comment)
1. Use [segment_volume](https://github.com/ivadomed/ivadomed/blob/69c8151d720445bfc51be40215d31c5414af5c22/ivadomed/inference.py#L311) to run the prediction and output NifTI files. The function also returns a list of nibabel objects and list of target_suffix for each class.
2. Those lists should then be used in [pred_to_png](https://github.com/ivadomed/ivadomed/blob/69c8151d720445bfc51be40215d31c5414af5c22/ivadomed/inference.py#L210) to produce the PNG segmentations (1 for each class).

**segment_volume options:**
For microscopy, the relevant options are:
- 'PixelSize': (list of float) List of microscopy PixelSize in micrometers . Length 2 ex: [PixelSizeX, PixelSizeY].
- 'overlap_2D': (list of int) List of overlaps in pixels for 2D patching. Length 2 ex: [overlapX, overlapY]. By default, the overlap between patches will be the same as the one set for training in the config file, but it can be overriden with this parameters. In the model I provided, the overlap is [48, 48].
- 'binarize_maxpooling': (bool) Used to binarize predictions with a multi-class model. Again, this parameters overrides the one from the config file. In the model I provided, 'binarize_maxpooling' is already True.

**Comment by mariehbourget** [comment]
FYI: the name of the pixel size option in `segment_volume` has changed from `PixelSize` to `pixel_size` to match the ivadomed's convention (updated in the comment above).

**Comment by mathieuboudreau** [comment]
Currently, 4 tests fail in the v4 branch. 

```
=========================== short test summary info ============================
FAILED test/test_integrity_test.py::TestCore::test_integrity_test_script_runs_successfully
FAILED test/testing/test_statistics_generation.py::TestCore::test_metrics_single_wrapper_runs_successfully_and_outfile_exists
FAILED test/testing/test_statistics_generation.py::TestCore::test_metrics_classic_wrapper_runs_successfully_and_outfile_exists
FAILED test/testing/test_statistics_generation.py::TestCore::test_metrics_class_loads_stats_table
```

Here's a short explanation for each:

1. test_integrity_test_script_runs_successfully
  * This line including `axon_segmentation` (deleted) is called here https://github.com/neuropoly/axondeepseg/blob/3c903dc9b04c98f8c81277c37ba97e14ed03e4d8/AxonDeepSeg/integrity_test.py#L44
  * Possible solutions
    * Write a function called `axon_segmentation` that uses the same args that wraps around IVADOMED
    * Write a new function that wraps around IVADOMED (or call IVADOMED directly) and update the call here
2. test_metrics_single_wrapper_runs_successfully_and_outfile_exists
  * This line including `axon_segmentation` (deleted) is called here https://github.com/neuropoly/axondeepseg/blob/3c903dc9b04c98f8c81277c37ba97e14ed03e4d8/AxonDeepSeg/testing/statistics_generation.py#L205
  * Possible solutions
    * See above in point 1.
3. test_metrics_classic_wrapper_runs_successfully_and_outfile_exists
  * This line including `axon_segmentation` (deleted) is called here https://github.com/neuropoly/axondeepseg/blob/3c903dc9b04c98f8c81277c37ba97e14ed03e4d8/AxonDeepSeg/testing/statistics_generation.py#L205
  * Possible solutions
    * See above in point 1.
4. test_metrics_class_loads_stats_table
  * Missing file: 
  ``` ________________ TestCore.test_metrics_class_loads_stats_table _________________

self = <AxonDeepSeg.testing.statistics_generation.metrics object at 0x7f9e07737850>

    def load_models(self):
        for path in self.path_models:
    
            # If string, convert to Path objects
            path = convert_path(path)
    
            try:
>               with open(path / self.statistics_filename) as f:
E               FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/work/axondeepseg/axondeepseg/AxonDeepSeg/models/default_SEM_model/model_statistics_validation.json'
```
  * Reason: Unsure for now. The model folder in OSF does not contain this file (https://osf.io/sv7u2/), so maybe it's something that was generated during this test or a previous test.
  *  It is present in the class here https://github.com/neuropoly/axondeepseg/blob/5fb6a2e2f10a372cf4b35a7ee85f52bbf8da76f3/test/testing/test_statistics_generation.py#L35 and here https://github.com/neuropoly/axondeepseg/blob/5fb6a2e2f10a372cf4b35a7ee85f52bbf8da76f3/test/testing/test_statistics_generation.py#L52

**Comment by mariehbourget** [comment]
@mathieuboudreau, as discussed in this ivadomed [issue](https://github.com/ivadomed/ivadomed/issues/873), I trained a new model to continue the integration available [here](https://drive.google.com/drive/folders/1AMwIA0Pr8xZpHuoD2rqvs_lCMnTLESjo). This model (onnx and pt) should not throw any errors when calling `segment_volume` with your code:

```
from ivadomed import inference as imed_inference

path_model="/home/GRAMES.POLYMTL.CA/u097381/ads_ivadomed/axondeepseg/AxonDeepSeg/models/model_seg_rat_axon-myelin_sem"
input_filenames = ["/home/GRAMES.POLYMTL.CA/u097381/ads_ivadomed/axondeepseg/AxonDeepSeg/models/default_SEM_model/data_test/image.png"]
options = {"pixel_size": [0.13, 0.13], "overlap_2D": [48, 48], "binarize_maxpooling": True}

nii_lst, target_lst = imed_inference.segment_volume(path_model, input_filenames, options=options)

imed_inference.pred_to_png(nii_lst, target_lst, "<path_to_the_source_file>/image")
```

Notes:
- I added the last line so you can see the results of the segmentations in PNG files alongside the original file.
- The default model values of `overlap_2D = [12, 12]` and `binarize_maxpooling = True` can be overridden busing the options of segment_volume.
- The `pixel_size` should be a 2-number array ex: `[0.13, 0.13]`. The single float (`0.13`) behavior is supported during development of the Microscopy BEP but will be remove in the future.
- By default, ivadomed will take the `onnx` version if present in `path_model`, and take the `pt` otherwise.

**Comment by mariehbourget** [comment]
@mathieuboudreau,
a first version of the OM model is available [here](https://drive.google.com/drive/folders/1eCNLv-DUfOiutiYHGBq6K8E5PYhepNVO).

I included a READM.md for the repo.
