### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#53]
See: https://github.com/neuropoly/axondeepseg/pull/50#issuecomment-368222807

**Comment by alzaia** [comment]
The installation from PyPI (using ```pip install axondeepeg```) is OK for a first-time user/installation. However, what we did not consider is that the software will change often (so new PyPI wheels) so users will want to just update it. 

Also, for the installation, we chose to install it from PyPI wheels. This means that the user does not need to clone the git repo to do that. Another approach would be to clone (or pull) the axondeepseg repo, and then do as @perone suggested (```pip install -e .```). We can modify the installation procedure, or offer both approaches. What do you think?

**Comment by jcohenadad** [comment]
i would go with cloning axondeepseg repos and do `pip install -e .`. I would absolutely not propose two options: this will confuse users.
@perone any thoughts?

**Comment by perone** [comment]
There are two different things that we should have a clear separation: development and application use. 

For the development, the `pip install -e .` is the traditional way to go, given that who is developing, testing, checking PRs wants immediate changes in the code to be reflected on their systems.

For final users, the installation should be: `pip install axondeepseg` to install the latest stable version. Now, if you want to release a version that isn't a final version for users (for testing or pre-release purposes), you should consider using a release candidate (RC) as recommended by the [versioning PEP](https://www.python.org/dev/peps/pep-0440/#pre-releases), so normal installation will install the latest stable version, but the release candidate can be installed if explicitly requested by the user such as in `pip install axondeepseg=0.4rc1` or something similar.

I think that this scheme would cover all use cases, or am I missing something ?

**Comment by jcohenadad** [comment]
Thank you @perone. That makes perfect sense. So, we should probably need to indicate to the user that they can install a specific version of ADS in the [help](https://neuropoly.github.io/axondeepseg/documentation.html#installing-axondeepseg).
We should probably also create a CHANGELOG that lists all modifications for each new release. 

Now regarding the indication of two types of installation for the user (stable or development). I think this could be explained in the help without too much confusion for the user.

@alzaia @perone do you agree with that plan?  @zougloub do you have any suggestions for us?

**Comment by perone** [comment]
For me it's ok !

**Comment by alzaia** [comment]
Also OK for me.

**Comment by jcohenadad** [comment]
👍 let's do it then :-)

**Comment by zougloub** [comment]
On the changelog, this is worth the read: http://keepachangelog.com/en/1.0.0/

**Comment by zougloub** [comment]
https://xkcd.com/1179/
