### ISSUE TITLE
New M1 mac does not support tensorflow bellow 2.x

### ISSUE THREAD

**Issue by AntoineRousseau97** [neuropoly/axondeepseg#536]
New M1 mac chip doesn't work with tensorflow 1.13.x. I searched for a solution but from what i read, M1's hardware simply does not work with tensorflow bellow 2.4 or so. Would it be possible/easy to upgrade AxonDeepSeg so it now works with a more recent version of tensorflow (2.4 or higher)? 

Thank you! :)

**Comment by jcohenadad** [comment]
Hi @AntoineRousseau97 we are currently refactoring ADS to depend on http://ivadomed.org/ (which is based on Pytorch, not TF). ETA: a few weeks.

**Comment by mathieuboudreau** [comment]
Hi @AntoineRousseau97,

Just wanted to add that this is priority for us, as some people in our lab (including myself) have new M1 machines as well.

**Comment by mathieuboudreau** [comment]
Hi @AntoineRousseau97,

I just wanted to let you know that version 4.0.0 of AxonDeepSeg has been released, and with it comes Mac M1 compatibility! It no longer uses tensorflow, so I will close this issue.
