### ISSUE TITLE
Discrepancy in morphometrics between v3 and v4

### ISSUE THREAD

**Issue by hermancollin** [neuropoly/axondeepseg#589]
**Describe the bug**
When comparing morphometrics obtained in v3 and v4, the solidity and orientation values differ.

**To Reproduce**
I computed morphometrics on the _image.png_ test image located in `axondeepseg/test/__test_files__/__test_demo_files__` and indeed every values are the same between versions except solidity and orientation.

![Screenshot_20220119_163714](https://user-images.githubusercontent.com/83031821/150218592-cb3c5dc7-b41d-4110-b394-716e1f55cee1.png)

**Comment by jcohenadad** [comment]
Good catch @hermancollin ! thank you for reporting it (and finding it)!

**Comment by mathieuboudreau** [comment]
Thanks @hermancollin ! After this is resolved but prior to merging, we'll need to add a test to catch a similar bug if it happens again.

**Comment by hermancollin** [comment]
> Good catch @hermancollin ! thank you for reporting it (and finding it)!

To be fair @mariehbourget caught this yesterday and asked me to look into it.

Now, as @mathieuboudreau noted, `scikit-image` was bumped from 0.14.2 to 0.18.3 in the v4 branch. The orientation and solidity values are both properties of the list returned by `skimage.measure.regionprops`. From regionprops doc:

> Deprecated since version 0.16.0: Use “rc” coordinates everywhere. It may be sufficient to call numpy.transpose on your label image to get the same values as 0.15 and earlier. However, for some properties, the transformation will be less trivial. ___For example, the new orientation is pi/2 plus the old orientation___

Indeed, from what I can see, if we add pi/2 to the v4 orientation, we get the same values as in v3.

**Comment by jcohenadad** [comment]
> To be fair @mariehbourget caught this yesterday and asked me to look into it.

ah, thank you for the clarification. Thank you both then 😊

**Comment by mathieuboudreau** [comment]
Since scikit image is permanently using this new convention, should we maybe consider adopting it too, at the cost of differences in values for orientation and solidity between ADS v4 and <v3?

**Comment by hermancollin** [comment]
For the solidity, it looks a bit more convoluted. This is how it's computed:
```python
def solidity(self):
        return self.area / self.area_convex
```
`area_convex` is in turn computed using `skimage.morphology.convex_hull_image`. Not sure what is happening exactly here but in skimage 0.18.0 this function was changed
> morphology.convex_hull_image now uses much less memory by checking hull inequalities in sequence (#5020)

Maybe this has something to do with it because the solidity values only differ by about 1% between v3 and v4.

But I agree with @mathieuboudreau that switching to the new convention should be considered.

**Comment by mariehbourget** [comment]
Thank you @hermancollin for looking into this!
I also agree that we should consider adopting the new convention. Because we are also updating the models with v4, it seems to me that it's the best possible time to do this.

**Comment by hermancollin** [comment]
Following the discussion we had in the meeting, we will use the new convention. Also, a test will be added to automatically catch morphometrics computation changes in the future.
