### ISSUE TITLE
Decrease of performance in latest merge of PR #50

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#59]
Data:
![unnamed_23 87nm](https://user-images.githubusercontent.com/2482071/36637190-05ee6f10-1a1a-11e8-9a80-38a87f0e1a2f.jpg)

Syntax:
~~~
axondeepseg -t TEM -i test/ -s 0.02387
~~~

commit 286dc698db156e71a7271a25016a442e8e2de450
![unnamed_23 87nm_segmented](https://user-images.githubusercontent.com/2482071/36637193-0c5b99fe-1a1a-11e8-815b-967693f2d657.png)

commit 759a45f581d2fd5ddd47ce845059f607466d3956
![unnamed_23 87nm_segmented](https://user-images.githubusercontent.com/2482071/36708732-c876c232-1bb7-11e8-90dd-da6f86b08e9d.png)

**Comment by jcohenadad** [comment]
no, what i would do instead is allow users to point to a single file instead of a folder. Otherwise, we will always face these kind of problems in the future (e.g., if the user decides to crop the data and have both images in the same folder, but he/she only want to segment one of the file).

**Comment by alzaia** [comment]
Yes, both ways are possible. You can put a folder as input and it will get all the images inside and segment them, or you can just put the path of an image and it will segment only that image. The folder version is useful when you have many images with the same pixel size.

So to resume:
- Only allow the user to use an image path as input (and not a folder path)
- For all pre-processings, generate temp file for the segmentation, and then delete it when it's done

**Comment by jcohenadad** [comment]
No, what I meant is that previously, when inputing a path+file name, it didn't work. It seems to be working now though. We should leave the possibility to have file name or folder name as input.

However, we should definitely not alter the original input image, so yes, you should work with a temp file.

**Comment by alzaia** [comment]
The discussion raised by this issue was resolved in PR #65
