### ISSUE TITLE
Duplication of images on Jupyter notebook

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#63]
The same image is displayed 3x at section 12:
https://github.com/neuropoly/axondeepseg/blob/master/notebooks/morphometrics_extraction.ipynb

**Comment by alzaia** [comment]
It is similar but not the same. The first one is only the axon mask, the 2nd one is axon mask overlay on image, the 3rd is axon mask +myelin overlay on image. 

I can remove the first 2 as they are 'included' in the 3rd.

**Comment by jcohenadad** [comment]
yes pls remove because it is confusing

**Comment by alzaia** [comment]
This was resolved with PR #64
