### ISSUE TITLE
Change output names: axon_mask.png and myelin_mask.png

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#69]
In case the user has two files in the same folder, e.g. image1.png and image2.png, and he runs ADS on both images, then the output segmentations will overwrite results from the first image.

A suggestion is to output the following files:
~~~
xxx_axon.png
xxx_myelin.png
xxx_axon-myelin.png
~~~
with xxx being the name of the input file.

**Comment by alzaia** [comment]
Fixed in PR #71
