### ISSUE TITLE
Local Jupyter notebook not seeing virtual environment packages/path

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#78]
**Branch**: [install_jupyter_debug]( https://github.com/neuropoly/axondeepseg/tree/install_jupyter_debug)

Hi all – new user/dev/neuropoly member here.

I came up on a small user experience bug related to the Jupyter notebooks while following the install instructions. The solution I found below is very (very) simple, but since all the forums I found discussing similar issues didn't point to this answer, I thought I'd be a bit more verbose.

**OS**: Mac OSX Sierra
**Default Python installation**: [Anaconda 3.6](https://www.anaconda.com)

Since I already had Python 3.6 installed as my default `python` version, and didn't want to give it up, I created my 2.7 virtual environment using Anaconda's `conda` command instead of `virtualenv` using this command:

`conda create -n ads_venv python=2.7`

(Another reason I prefer using Anaconda's virtual environment creator instead of `virtualenv` is that it gets stored into Anaconda's folder, and I can source it without the full path: e.g. `source activate ads_venv` instead of ` source ~/ads_venv/bin/activate`)

At this point, within the virtualenv and after pip installation of AxonDeepSeg, the integrity test passed correctly.

My issue came when I tried to open the Getting Started Jupyter notebook on my local computer. The notebook settings that was opening was not the same as the virtualenv (e.g. 3.6 instead of 2.7, and the AxonDeepSeg module was not in the path).

![jupyter](https://user-images.githubusercontent.com/1421029/38434363-a02cd05a-39a8-11e8-9550-6f97a252ba4c.png)

This was happening because the Jupyter version that was called was from the Anaconda directories from a previous installation, and so I think it was being opened outside my virtualenv (not fully sure what happened behind the scenes). Nonetheless, this issue was simply resolved for me by adding Jupyter to the [requirements.txt](https://github.com/neuropoly/axondeepseg/blob/4786b9aa72da9109cd3d66a225d77f86a9cacedd/requirements.txt) file so that it is installed within the venv.

![jupyter2](https://user-images.githubusercontent.com/1421029/38435157-6e0a5edc-39ab-11e8-85eb-05aaf2cd5a6b.png)

I added this to my branch, as well as a few other minor fixes/cleanup I encountered along the way.

**Comment by jcohenadad** [comment]
thanks a lot for addressing this issue @mathieuboudreau. Don't hesitate to open a PR already so we can start testing/reviewing the changes. Thanks!

**Comment by mathieuboudreau** [comment]
Closed – as discussed in PR #79, since Jupyter is not needed for the actual implementation of AxonDeepSeg, it's best not to include it in the requirements, and instead the documentation will be improved through issue #80 .
