### ISSUE TITLE
Make ADS Python 3.5x/3.6x compatible

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#92]
Current branch: [py2to3](https://github.com/neuropoly/axondeepseg/tree/py2to3)

Issue raised by @jcohenadad in issue #91 .

The first thing I think needs to be decided is if we want to make ADS compatible with both Python 2.7 and 3.5x/3.6x. The resources I found (below) seem to be contradicting themselves over which is preferred in the community. Dual compatibility is a bit messier to maintain in the long term; while it's (relatively) simple to convert the code for dual compatibility, the problematic issue will then be that each dev on the future project will have to know all the little tricks needed for dual compatibility (see cheat sheet below), rather than using just Python 3's strengths.

Most resources agree that the next step is to have comprehensive test coverage of the repo. I've already started working on this in branch [unit_tests](https://github.com/neuropoly/axondeepseg/tree/unit_tests), which handles issue #76. I've also added a [coveralls.io](coveralls.io) badge to the branch that gets evaluated in the Travis test, which currently asses the test coverage in that branch to be [15 %](https://coveralls.io/github/neuropoly/axondeepseg) (only using the unit tests, not the integration test `integrity_test.m`). Once we have a test coverage closer to 100% (most people agree online that exactly 100% might be nitpicky, so >80-90% is good to aim for), then it will be easier to determine if the code functions well after being converted for 3.5/3.6x or dual 2.7/3.x.

Resources:

* [Porting Python 2 Code to Python 3](https://docs.python.org/3/howto/pyporting.html)
* [Supporting Python 2 and 3 without 2to3 conversion](http://python3porting.com/noconv.html)
    * This is somewhat of a badly titled article, because the first step they suggest is actually to do `2to3` conversion, and then debug the code until it runs in a Python 2.7 environment.
* [Cheat sheet for writing Python 2-3 compatible code](http://python-future.org/compatible_idioms.html)

**Comment by perone** [comment]
Completely agree, Python 3 is the way to go, a lot of libraries are deprecating Python 2 in the following 1 or 2 years so it's a good move.

**Comment by mathieuboudreau** [comment]
Sounds good – that should make things simpler/cleaner.

**Comment by alzaia** [comment]
So moving to Python 3 now will just save us a lot of issues in the long term, before the project and code become larger.

**Comment by mathieuboudreau** [comment]
Resolved in release v2.0.
